/**
 * BRIQUES NARRATIVES - tables d'éléments pré-écrits pour garantir la
 * diversité entre les romans. À chaque création de partie, Fable
 * PIOCHE 1 élément par catégorie (au hasard) et les IMPOSE à la
 * story bible : le modèle ne choisit plus tout seul, il intègre.
 * Anti-clichés : chaque entrée est volontairement singulière.
 * Les éléments sont des INDICES (1 ligne), le roman les développe.
 */

/** 50 lieux de départ (où l'histoire commence). */
export const LIEUX: string[] = [
  'un atelier de restauration de pendules au bord d\'un canal gelé',
  'une bibliothèque municipale qui ne ferme qu\'une nuit par an',
  'un hôtel de montagne déserté depuis l\'avalanche de 1974',
  'un marché aux puces géant sous un viaduc autoroutier',
  'une conserverie de sardines reconvertie en salle de concert',
  'un poste de garde forestier au milieu d\'une forêt plantée en damier',
  'une gare de triage où les trains ne s\'arrêtent plus',
  'un immeuble haussmannien dont chaque étage cache un atelier d\'artiste',
  'une station-service sur la route nationale, ouverte 24h/24 depuis 1962',
  'un phare désaffecté transformé en musée des naufrages',
  'une maison de retraite au bord d\'un golf abandonné',
  'un cinéma de quartier qui projette le même film depuis quarante ans',
  'un jardin botanique fermé au public depuis un scandale',
  'une caserne de pompiers promue au rang de musée',
  'un entrepôt portuaire rebaptisé espace culturel, jamais inauguré',
  'un village perché dont le pont unique menace de céder',
  'une école désaffectée dont les tableaux portent encore la dernière leçon',
  'un camping désert en bord de falaise, au mois de novembre',
  'une imprimerie à l\'ancienne spécialisée dans les faire-part',
  'un refuge de haute montagne gardé par un ermite',
  'un aqueduc romain qui traverse encore la ville',
  'une clinique vétérinaire dans une ancienne chapelle',
  'un funiculaire hors service reliant deux quartiers oubliés',
  'une librairie de poche sous les arcades d\'une place',
  'un port de pêche où les bateaux rentrent de plus en plus tôt',
  'une serre municipale géante remplie d\'orchidées',
  'un théâtre de marionnettes au fond d\'une cour pavée',
  'une laverie automatique ouverte toute la nuit près de la gare',
  'un château d\'eau peint en bleu au sommet d\'une colline',
  'une mairie de village aux archives jamais classées',
  'un fort Vauban transformé en colonie de vacances',
  'une brasserie artisanale au sous-sol d\'un immeuble',
  'un observatoire astronomique amateur sur un toit',
  'une île sablonneuse qui émerge à marée basse',
  'un atelier de dorure et de restauration de cadres',
  'une poste de montagne où le facteur distribue depuis cent ans',
  'un bassin de radoub pour vieux chalutiers',
  'une grotte ornée réouverte après un glissement de terrain',
  'un manège de chevaux de bois dans un parc abandonné',
  'une tour de guet médiévale au milieu de vignes',
  'un refuge pour animaux tenu par une ancienne vétérinaire',
  'une passerelle suspendue au-dessus d\'un fjord urbain',
  'un grenier municipal plein de commodes à secrets',
  'une roulotte de cirque garée dans un champ depuis des années',
  'un kiosque à musique où l\'on répète un orchestre invisible',
  'une usine de biscuits dont le four ne s\'éteint jamais',
  'un pont-levis urbain qu\'on ne lève plus que pour les péniches',
  'une auberge de jeunesse dans un ancien couvent',
  'un silo à grains transformé en galerie d\'art',
  'une gare maritime désaffectée qui sent encore le goudron',
];

/** 50 événements de bascule (le trouble qui déclenche l'histoire). */
export const EVENEMENTS: string[] = [
  'tous les pendules de la ville s\'arrêtent à la même seconde',
  'un paquet arrive sans expéditeur, avec une date future inscrite dessus',
  'quelqu\'un repeint la porte du héros en rouge chaque nuit, sans laisser de traces',
  'un journal intime paraît par chapitres dans la boîte aux lettres, racontant le lendemain',
  'une émission de radio locale diffuse un message codé qui porte sur le héros',
  'des miroirs de la ville reflètent un bâtiment qui n\'existe pas',
  'un chat adopté la veille mène le héros jusqu\'à une cachette murale',
  'le sol de la cave cède sur une salle qui ne figure sur aucun plan',
  'une plainte anonyme révèle que le héros a signé un document en 1987',
  'le héros reçoit un faire-part de décès à son propre nom, daté de demain',
  'toutes les horloges de la ville tournent à rebours pendant une heure',
  'un tableau du musée change de personnage chaque matin',
  'un chantier routier met au jour une porte en pierre scellée à la cire',
  'un message en morse clignote dans les phares d\'une voiture épave',
  'les fleurs d\'un jardin public fleurissent en plein hiver, formant un mot',
  'un inconnu rend au héros un objet perdu il y a vingt ans, en sachant son nom',
  'une grève des transports paralyse la ville le jour d\'une éclipse',
  'un employé de la mairie découvre un double de la ville dans les archives',
  'le héros gagne un concours auquel il ne s\'est jamais inscrit',
  'un métro fantôme s\'arrête à une station rayée des plans',
  'une photographie de classe montre le héros, vingt ans avant sa naissance',
  'un incendie sans flammes détruit une seule maison, la sienne',
  'un naufrage au large libère des caisses portant le nom du héros',
  'un ascenseur s\'ouvre sur un étage qui n\'existe plus depuis la guerre',
  'la plus vieille cloche de la ville sonne à minuit, toute seule, trois soirs de suite',
  'un film amateur retrouvé montre la ville d\'aujourd\'hui, tourné en 1950',
  'une série de petits cailloux blancs mène à une tombe fraîchement creusée',
  'un maître-nageur retrouve un message dans une bouteille consignée à son nom',
  'le héros surprend une conversation sur lui, tenue dans une langue morte',
  'une carte postale arrive avec le cachet d\'une ville engloutie',
  'un test ADN révèle une parenté impossible avec une famille éteinte',
  'un pianiste aveugle répète chaque nuit une chanson que seule la mère du héros connaissait',
  'une panne générale de courant laisse la ville sans son bruit de fond habituel',
  'un navire mouille au large sans jamais entrer au port, pendant des semaines',
  'le héros retrouve son propre message vocal, mais enregistré par une voix d\'enfant',
  'un gardien de phare oublié allume toutes les nuits une lumière qu\'on ne voit nulle part ailleurs',
  'une lettre recommandée exige la restitution d\'un objet que le héros n\'a jamais eu',
  'le bruit sourd d\'une machinerie se fait entendre sous les fondations du quartier',
  'une jumelle posée sur un banc pointe exactement vers la fenêtre du héros',
  'un roman policier décrit, chapitre par chapitre, des crimes qui vont avoir lieu',
  'la pluie tombe seulement au-dessus d\'une parcelle précise du cimetière',
  'un télégraphe restauré s\'anime et transmet des messages d\'une autre époque',
  'le héros découvre une chambre en plus dans son appartement, identique mais à l\'envers',
  'un concours de photos amateur organise la révélation d\'une pellicule de quarante ans',
  'une sirène d\'usine, muette depuis trente ans, retentit une seule fois à l\'aube',
  'le héros est élu président d\'une association qu\'il ne connaît pas',
  'un train spécial traverse la gare sans s\'arrêter, tous les vendredis, avec un wagon éteint',
  'un puits tari se remet à couler, et l\'eau est tiède et salée',
  'les hirondelles désertent la ville en plein été, sauf une place où elles tournoient sans poser',
  'une inondation creuse le sol et révèle un escalier qui descend très bas',
];

/** 50 mystères centraux (l\'énigme que l\'histoire élucide). */
export const MYSTERES: string[] = [
  'pourquoi tous ceux qui ont restauré le vieux buffet ont-ils disparu un par un',
  'ce que cache vraiment le mur aveugle du fond de la cave',
  'qui envoie les questions du jeu de piste dans le journal local',
  'pourquoi le niveau de l\'étang ne baisse jamais malgré les canaux',
  'ce que cherchait l\'expédition dont personne n\'est revenu, et qu\'elle a trouvé',
  'qui marque les noms sur les pierres du chemin, et pourquoi',
  'ce qu\'est devenu le contenu du coffre de la maison de famille, scellé depuis 1918',
  'pourquoi les cartes anciennes dessinent une rue qui n\'existe plus depuis la mise en eau',
  'qui allume les lampes de la ville haute quand le héros est seul là-haut',
  'ce que signifie le mot gravé sous le banc du square, visible seulement à contre-jour',
  'pourquoi les habitants prononcent le nom de la colline avec un accent différent',
  'ce que fabriquait l\'usine avant qu\'on efface toutes ses archives',
  'qui a reconstruit le pont dans la nuit après l\'effondrement, et avec quelles pierres',
  'la raison pour laquelle la radio d\'époque capte une station qui émet depuis un studio vide',
  'pourquoi tous les enfants nés un certain hiver portent le même grain de beauté',
  'ce que visait la ligne de tir gravée sur le mur du fort',
  'qui déplace les pièces de l\'échiquier géant de la place, une nuit sur deux',
  'la nature du chant que les plongeurs entendent à quinze mètres',
  'pourquoi le maître d\'école d\'autrefois notait le temps qu\'il fera, et s\'est toujours trompé',
  'ce que contient la malle que le portier refuse de livrer depuis trente ans',
  'qui a écrit les lettres d\'amour signées d\'un nom mort avant leur date',
  'pourquoi le sommet du phare est peint en blanc alors que tous les autres sont rouges',
  'ce que signifie le cercle tracé autour du village sur la carte de 1847',
  'la raison du retour périodique des feux de brouillard, en pleine terre',
  'qui a fait sceller le deuxième escalier du théâtre, et ce qu\'il dessert',
  'pourquoi les oiseaux évitent un cercle précis dans la forêt',
  'ce que l\'armée cherchait en perçant le plateau, et si elle l\'a trouvé',
  'qui paie l\'entretien de la chapelle privée où personne n\'entre',
  'ce que devient l\'eau détournée du moulin à travers le souterrain',
  'pourquoi les machines de l\'imprimerie s\'arrêtent toutes à la même minute chaque jour',
  'la signification du signal que la vigie allume trois fois par hiver',
  'ce que renferme la chambre condamnée de l\'auberge, verrouillée de l\'intérieur',
  'qui répare le ponton du lac chaque printemps, depuis la mort de son propriétaire',
  'pourquoi la cloche portant le nom d\'un saint inconnu ne répond pas aux inscriptions',
  'ce que dissimule le double fond de l\'armoire du musée municipal',
  'qui a gravé la fresque sous le plâtre lors du chantier de ravalement',
  'ce que sans le courant la rivière amène chaque année au même endroit du gué',
  'pourquoi la gare abandonnée garde sur son horloge l\'heure d\'un accident',
  'ce que le collectionneur achetait dans la ville tous les ans, sans jamais ouvrir les cartons',
  'la raison des trois coups frappés contre la coque du ponton, les soirs d\'orage',
  'qui a planté la haie d\'épines en cercle autour du noyer, et pourquoi',
  'ce que signifie le portrait retourné dans le grenier du presbytère',
  'pourquoi tous les puits de la vallée donnent une eau au goût de fer depuis l\'année du grand gel',
  'ce qu\'il y avait à l\'emplacement de la flaque qui ne sèche jamais, avant la route',
  'qui a laissé la valise dans le consigne de la gare, avec un billet jamais pris',
  'ce que cherchait le promeneur qui traçait des cartes chaque dimanche sur le même chemin',
  'pourquoi le ciel au-dessus de l\'usine est violet certains soirs, par temps calme',
  'ce que le vieux joueur d\'orgue de barbarie répète dans sa mélodie depuis cinquante ans',
  'qui coupe les bourgeons du mûrier ancien, à cause duquel on a détourné la route',
  'ce que signifie la marque qui revient sur toutes les portes du quartier, toujours au même angle',
];

/** 50 secrets ou failles du héros (ce qui le définit). */
export const SECRETS: string[] = [
  'le héros est daltonien mais s\'est toujours débrouillé pour le cacher',
  'le héros a rendu un examen à la place de son frère, et la dette n\'est jamais réglée',
  'le héros garde les clés d\'un appartement qui n\'existe plus',
  'le héros écrit des lettres à un correspondant imaginaire depuis l\'enfance',
  'le héros a perdu la mémoire de deux années entières, les années 19',
  'le héros sait faire beaucoup de choses, mais oublie toujours les visages',
  'le héros a promis à un mourant de transmettre un message, et ne l\'a jamais fait',
  'le héros collectionne les pierres lisses et compte dessus quand il a peur',
  'le héros a fui un lieu précis, un soir, et n\'y est jamais retourné',
  'le héros entend une cassette de sa propre voix, mais ne se souvient pas l\'avoir enregistrée',
  'le héros ne dort jamais plus de trois heures sans allumer la lumière',
  'le héros connaît par cœur des itinéraires qu\'il n\'a jamais empruntés',
  'le héros a une cicatrice dont personne n\'a jamais vu la cause',
  'le héros répond aux lettres mortes, aux adresses qui n\'existent plus',
  'le héros est incapable de dire non aux gens qui prononcent son nom complet',
  'le héros a vu quelque chose un soir de brouillard, et a juré de ne jamais en parler',
  'le héros garde dans sa poche une carte à jouer marquée de la main de son grand-père',
  'le héros a appris à lire sur des journaux qui dataient d\'avant sa naissance',
  'le héros salue les statues la nuit, par habitude héritée d\'un secret',
  'le héros sait faire démarrer les moteurs à main, les horloges, les orgues - et rien d\'autre',
  'le héros a traversé une frontière sans papiers, un hiver lointain',
  'le héros ne supporte pas le son des cloches depuis un certain événement',
  'le héros a caché un objet important et s\'est interdit d\'en chercher l\'emplacement',
  'le héros entend un mot précis lorsque sa vie a basculé, et frissonne à chaque fois',
  'le héros répète parfois les phrases que disait quelqu\'un qu\'il a perdu',
  'le héros possède la moitié d\'une photographie déchirée et refuse de chercher l\'autre',
  'le héros a promis de ne plus jamais voler, sauf pour une seule raison',
  'le héros connaît une carte du ciel que personne d\'autre de son âge ne connaît',
  'le héros a été sauvé de l\'eau un hiver, par quelqu\'un parti ensuite',
  'le héros écrit chaque soir le mot du jour sur le même carnet, depuis dix ans',
  'le héros évite un carrefour précis sans savoir dire pourquoi',
  'le héros a menti une seule fois, gravement, et la vérité le rattrape',
  'le héros garde un sifflet qu\'on lui a donné en disant : tu en auras besoin',
  'le héros connaît la date exacte à ne jamais prononcer, mais pas ce qu\'elle cache',
  'le héros a hérité d\'un métier qu\'il n\'exerce pas et d\'un silence qu\'il porte',
  'le héros sait écouter les bruits de la nuit et les classer, sans jamais les nommer',
  'le héros a un double fond dans sa valise, et rien dedans',
  'le héros se souvient d\'avoir déjà rêvé la ville avant de la voir',
  'le héros a retenu un message qu\'on lui a chuchoté enfant, sans en comprendre un mot',
  'le héros rend visite à une tombe qui n\'a pas de nom, une fois par an',
  'le héros a laissé quelqu\'un partir, et se demande encore s\'il pouvait l\'arrêter',
  'le héros range dans un bocal les tickets de toutes les choses qu\'il n\'a jamais faites',
  'le héros a une peur particulière des photographies récentes',
  'le héros peut reconnaître le temps qu\'il fera dans trois jours, et se trompe rarement',
  'le héros a promis de tenir un phare allumé, sans savoir pourquoi ni pour qui',
  'le héros garde un billet de train pour une ville dont il n\'a jamais trouvé le nom',
  'le héros a un jour écouté une conversation qu\'il n\'aurait pas dû, et ça a tout changé',
  'le héros connaît par cœur une chanson à moitié oubliée, et ne sait pas d\'où elle vient',
  'le héros a tracé une ligne sur une carte pour délimiter ce qu\'il s\'autorise à chercher',
  'le héros possède un carnet d\'adresses où tous les noms sont effacés sauf un',
];

/** 50 antagonistes / menaces (celui ou ce qui s\'oppose). */
export const ANTAGONISTES: string[] = [
  'une directrice de musée qui collectionne les œuvres disparues',
  'un ancien ingénieur qui veut prouver que la ville a été construite sur une erreur',
  'un journaliste qui ne publie les vérités que trop tard, et le sait',
  'une société qui rachète les silences des gens, maison par maison',
  'un gardien de nuit qui connaît tous les passages secrets, sauf le dernier',
  'un peintre qui reproduit les bâtiments avant leur destruction, avec un délai',
  'un archiviste qui efface les registres pour préserver ce qu\'il appelle l\'ordre',
  'un notaire qui détient les testaments de tout le quartier, et s\'en sert',
  'une voix enregistrée qui donne des ordres et ne se tait jamais',
  'un ordre religieux local qui conserve un objet dont personne ne parle',
  'une ancienne institutrice qui sait, pour chaque habitant, le mot qui le brise',
  'un batelier qui refuse de transporter certaines marchandises pour de bonnes raisons',
  'un collectionneur qui achète les souvenirs, pas les objets',
  'une coopérative qui décide du destin des terres communes, sans convocation',
  'un météorologue amateur dont les prévisions annoncent des événements précis',
  'un commissaire-priseur qui organise une vente où tout le quartier est le lot',
  'une famille qui considère le territoire comme son pré carré depuis six générations',
  'un ingénieur de l\'eau qui détourne les ruisseaux pour des raisons anciennes',
  'un pharmacien qui tient le registre de toutes les maladies du village',
  'un vitrier qui observe la ville à travers les fenêtres, et note tout',
  'une chorale qui répète la même chanson depuis si longtemps qu\'elle change les gens',
  'un gendarme retraité qui archive les affaires non résolues et les relit',
  'une même personne qui se présente sous des noms différents dans chaque quartier',
  'un entrepreneur qui veut percer la colline pour y trouver autre chose que du calcaire',
  'une radio pirate qui diffuse des aveux que personne n\'a faits',
  'un orphelinat administré par une directrice qui garde les dossiers de chaque naissance',
  'un facteur qui trie le courrier par destinataire réel, pas par adresse',
  'un cartographe qui redessine la ville selon ce qu\'elle devrait être',
  'une scierie qui coupe les arbres marqués d\'une encoche ancienne',
  'un clocher qui sonne pour couvrir des bruits qu\'il ne faut pas entendre',
  'une amicale des anciens qui gère les souvenirs mieux que la municipalité',
  'un nageur de fond qui connaît le lac par en dessous mieux que personne',
  'une photographe qui développe des portraits de gens qui n\'ont pas encore posé',
  'un voiturier qui garde les clés de toutes les voitures volées, et les rend une par une',
  'une école de dressage animal qui apprend aux bêtes à ne pas aboyer la nuit',
  'un apiculteur dont les ruches bourdonnent toujours du même côté de la vallée',
  'une couturière qui raccommode les vêtements et connaît les lieux par les tissus',
  'un contrebassiste dont la musique fait vibrer un bâtiment précis de la ville',
  'une fédération de pêcheurs qui gère les profondeurs comme un trésor',
  'un rémouleur qui affûte, et qui n\'est pas fatigué de passer toujours au même endroit',
  'une institution qui garde les jumeaux du village séparés, sans explication',
  'un architecte qui repasse sur les plans anciens avec les changements qu\'il impose',
  'un liftier d\'un grand hôtel qui connaît l\'immeuble par les étages qu\'on lui cache',
  'une postière qui retient les lettres adressées à des morts, pour les bonnes raisons',
  'un orfèvre qui refond les médailles de baptême de toute la région',
  'une fanfare qui occupe la place chaque dimanche pour couvrir les silences',
  'un ex-employé des compteurs qui connaît la consommation exacte de chaque nuit',
  'une clinique privée qui achète les dossiers de santé et les archive sous clé',
  'un régisseur de théâtre qui garde le bâtiment de l\'intérieur, sauf une loge',
  'une bénévole de la brocante qui sait exactement ce que chaque objet racontait aux vivants',
];

/** 50 objets-signaux (élément visible, souvent au cœur de l\'intrigue). */
export const OBJETS: string[] = [
  'une lunette de théâtre en ivoire dont personne ne se sert',
  'un badge de plongeur numéroté 13, jamais porté',
  'une clé de voûte marquée d\'un prénom inconnu',
  'un gramophone doré qui joue encore, malgré le sable',
  'une flûte en roseau taillée la veille d\'un départ',
  'un paquet de lettres nouées d\'un ruban bleu, toutes cachetées',
  'un sablier qui se retourne tout seul quand la marée monte',
  'un coffret à musique qui joue un air écrit pour une seule personne',
  'une carte routière barrée de traits rouges, jaunie',
  'un violon sans cordes, dans son étui de voyage',
  'une montre de gousset arrêtée sur l\'heure d\'un événement',
  'un plan de table d\'un banquet qui n\'a jamais eu lieu',
  'une ancre miniature posée sur la cheminée, des algues encore fraîches',
  'un catalogue de graines édité l\'année d\'une grande gelée',
  'une lampe de mineur transformée en lampe de chevet',
  'un billet de loterie jamais gratté, qu\'on garde par superstition',
  'une maquette de bateau à mi-construction, arrêtée net',
  'une boussole qui pointe vers le village au lieu du nord',
  'un moulin à café qui moud encore des grains d\'un autre siècle',
  'une paire de jumelles de théâtre avec une lentille rayée en croix',
  'un registre de baptême à moitié rempli, arrêté à la lettre M',
  'un sifflet de régulateur ferroviaire, en laiton noirci',
  'une carte postale de la ville signée d\'une initiale inconnue',
  'un télescope de marin aux lentilles vert-de-grisées',
  'un carnet de timbres commencé et abandonné à la page des oiseaux',
  'une paire de gants de lavandière, enfilés pour la dernière fois un mardi',
  'un moulinet de pêche en os, souvenir ou relique',
  'une mesure à grains graduée en anciennes livres',
  'un pavillon de corne de brume, fendu sur le côté',
  'une loupe de graveur au manche d\'ébène usé par une seule main',
  'un calendrier perpétuel arrêté sur le mois de février',
  'un billet de train pour une gare fermée la semaine suivante',
  'une clochette de vache marquée au fer d\'une ferme disparue',
  'un encrier de voyage avec de l\'encre encore liquide',
  'un sextant solaire dont le verre a gardé la trace d\'un doigt',
  'une hache d\'abordage polie par des années de repos',
  'un carnet de recettes agricoles annoté d\'une autre main',
  'un rosaire de corail trouvé dans un fond de tiroir',
  'un boulet de canon au pied d\'une statue de soldat',
  'un passeport à l\'encre pâlie, sans photo',
  'une girouette en forme de bateau qui indique une direction impossible',
  'un gant de gardien de phare, trois doigts coupés',
  'une boîte à ouvrage avec des aiguilles de toutes tailles, sauf les plus fines',
  'un marteau de tonnelier marqué d\'une date de naissance',
  'un cachet de cire portant des armoiries effacées',
  'un thermomètre de serriste qui fige à une température étrange',
  'un plateau de balance en laiton, gravé d\'un poids impossible',
  'un couteau de berger à la lame encore huilée',
  'une lanterne sourde qu\'on n\'allume que pour descendre',
  'un plomb de douane ancien, lisant trop clairement un nom trop net',
];

/** 30 destinations / fins visées (où l\'histoire emmène le lecteur). */
export const DESTINATIONS: string[] = [
  'comprendre que l\'héritage qu\'il cherche n\'est pas une chose mais un choix',
  'découvrir que la clé de tout était sous ses yeux depuis le premier jour',
  'accepter qu\'il ne peut pas sauver les autres sans d\'abord se sauver lui-même',
  'révéler que la légende du lieu est vraie, mais pas de la façon dont on la raconte',
  'défaire une promesse faite à contrecœur avant qu\'elle ne devienne un serment',
  'montrer que la vérité protège mieux que le silence',
  'apprendre qui il est vraiment en abandonnant tout ce qu\'il croyait être',
  'faire revenir la confiance dans un village qui ne croyait plus à rien',
  'résoudre un vieux compte sans jamais révéler ce qu\'il a vu',
  'choisir, enfin, entre la fidélité au passé et la liberté',
  'empêcher une répétition exacte, et inventer une fin nouvelle',
  'découvrir que l\'adversaire cherchait la même chose que lui, pour d\'autres raisons',
  'faire parler un lieu qui détient la mémoire de plusieurs générations',
  'rendre à la communauté ce qu\'un secret lui avait pris',
  'franchir le seuil qu\'il s\'était juré de ne jamais franchir',
  'réparer une rupture qui dure depuis si longtemps qu\'on a oublié la cause',
  'transformer une malédiction en récit, puis en choix',
  'montrer que la valeur d\'une chose ne se mesure pas à son prix',
  'découvrir que le chemin qu\'il fuyait était le seul à mener au repos',
  'prouver qu\'un engagement passé n\'interdit pas de choisir son avenir',
  'faire la lumière sur une vérité que tous préféraient taire',
  'réapprendre à faire confiance à sa propre mémoire',
  'délivrer un lieu de son passé sans le détruire',
  'comprendre que garder un secret peut être un acte de courage quand il protège',
  'atteindre l\'endroit que toutes les cartes oublient, et en revenir',
  'rétablir un équilibre rompu il y a longtemps par une décision précipitée',
  'donner un nom à la chose que tout le monde évite de nommer',
  'découvrir que la vraie richesse du lieu n\'a jamais été celle qu\'on cherchait',
  'faire admettre à la ville qu\'elle peut changer sans se renier',
  'trouver la force de dire ce qu\'il n\'a jamais osé, à temps',
];

/**
 * Toutes les tables réunies, pour un tirage simplifié.
 * Attention : le contenu est en français, avec apostrophes typographiques
 * échappées - ne pas reformater.
 */
export const BRIQUES = {
  lieux: LIEUX,
  evenements: EVENEMENTS,
  mysteres: MYSTERES,
  secrets: SECRETS,
  antagonistes: ANTAGONISTES,
  objets: OBJETS,
  destinations: DESTINATIONS,
} as const;

/** Tire n éléments distincts d'une table, au hasard. */
export function piocher(table: readonly string[], n = 1): string[] {
  const pool = [...table];
  const picks: string[] = [];
  for (let i = 0; i < n && pool.length > 0; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    picks.push(pool.splice(idx, 1)[0]);
  }
  return picks;
}