/**
 * BRIQUES NARRATIVES - tables d'éléments pré-écrits pour garantir la
 * diversité entre les romans. À chaque création de partie, Fable
 * PIOCHE 1 élément par catégorie (au hasard) et les IMPOSE à la
 * story bible : le modèle ne choisit plus tout seul, il intègre.
 * Anti-clichés : chaque entrée est volontairement singulière.
 * Les éléments sont des INDICES (1 ligne), le roman les développe.
 */

/** 50 lieux de départ (où l'histoire commence). */
export const LIEUX: string[] = [
  'un atelier de restauration de pendules au bord d\'un canal gelé',
  'une bibliothèque municipale qui ne ferme qu\'une nuit par an',
  'un hôtel de montagne déserté depuis l\'avalanche de 1974',
  'un marché aux puces géant sous un viaduc autoroutier',
  'une conserverie de sardines reconvertie en salle de concert',
  'un poste de garde forestier au milieu d\'une forêt plantée en damier',
  'une gare de triage où les trains ne s\'arrêtent plus',
  'un immeuble haussmannien dont chaque étage cache un atelier d\'artiste',
  'une station-service sur la route nationale, ouverte 24h/24 depuis 1962',
  'un phare désaffecté transformé en musée des naufrages',
  'une maison de retraite au bord d\'un golf abandonné',
  'un cinéma de quartier qui projette le même film depuis quarante ans',
  'un jardin botanique fermé au public depuis un scandale',
  'une caserne de pompiers promue au rang de musée',
  'un entrepôt portuaire rebaptisé espace culturel, jamais inauguré',
  'un village perché dont le pont unique menace de céder',
  'une école désaffectée dont les tableaux portent encore la dernière leçon',
  'un camping désert en bord de falaise, au mois de novembre',
  'une imprimerie à l\'ancienne spécialisée dans les faire-part',
  'un refuge de haute montagne gardé par un ermite',
  'un aqueduc romain qui traverse encore la ville',
  'une clinique vétérinaire dans une ancienne chapelle',
  'un funiculaire hors service reliant deux quartiers oubliés',
  'une librairie de poche sous les arcades d\'une place',
  'un port de pêche où les bateaux rentrent de plus en plus tôt',
  'une serre municipale géante remplie d\'orchidées',
  'un théâtre de marionnettes au fond d\'une cour pavée',
  'une laverie automatique ouverte toute la nuit près de la gare',
  'un château d\'eau peint en bleu au sommet d\'une colline',
  'une mairie de village aux archives jamais classées',
  'un fort Vauban transformé en colonie de vacances',
  'une brasserie artisanale au sous-sol d\'un immeuble',
  'un observatoire astronomique amateur sur un toit',
  'une île sablonneuse qui émerge à marée basse',
  'un atelier de dorure et de restauration de cadres',
  'une poste de montagne où le facteur distribue depuis cent ans',
  'un bassin de radoub pour vieux chalutiers',
  'une grotte ornée réouverte après un glissement de terrain',
  'un manège de chevaux de bois dans un parc abandonné',
  'une tour de guet médiévale au milieu de vignes',
  'un refuge pour animaux tenu par une ancienne vétérinaire',
  'une passerelle suspendue au-dessus d\'un fjord urbain',
  'un grenier municipal plein de commodes à secrets',
  'une roulotte de cirque garée dans un champ depuis des années',
  'un kiosque à musique où l\'on répète un orchestre invisible',
  'une usine de biscuits dont le four ne s\'éteint jamais',
  'un pont-levis urbain qu\'on ne lève plus que pour les péniches',
  'une auberge de jeunesse dans un ancien couvent',
  'un silo à grains transformé en galerie d\'art',
  'une gare maritime désaffectée qui sent encore le goudron',
];

/** 50 événements de bascule (le trouble qui déclenche l'histoire). */
export const EVENEMENTS: string[] = [
  'tous les pendules de la ville s\'arrêtent à la même seconde',
  'un paquet arrive sans expéditeur, avec une date future inscrite dessus',
  'quelqu\'un repeint la porte du héros en rouge chaque nuit, sans laisser de traces',
  'un journal intime paraît par chapitres dans la boîte aux lettres, racontant le lendemain',
  'une émission de radio locale diffuse un message codé qui porte sur le héros',
  'des miroirs de la ville reflètent un bâtiment qui n\'existe pas',
  'un chat adopté la veille mène le héros jusqu\'à une cachette murale',
  'le sol de la cave cède sur une salle qui ne figure sur aucun plan',
  'une plainte anonyme révèle que le héros a signé un document en 1987',
  'le héros reçoit un faire-part de décès à son propre nom, daté de demain',
  'toutes les horloges de la ville tournent à rebours pendant une heure',
  'un tableau du musée change de personnage chaque matin',
  'un chantier routier met au jour une porte en pierre scellée à la cire',
  'un message en morse clignote dans les phares d\'une voiture épave',
  'les fleurs d\'un jardin public fleurissent en plein hiver, formant un mot',
  'un inconnu rend au héros un objet perdu il y a vingt ans, en sachant son nom',
  'une grève des transports paralyse la ville le jour d\'une éclipse',
  'un employé de la mairie découvre un double de la ville dans les archives',
  'le héros gagne un concours auquel il ne s\'est jamais inscrit',
  'un métro fantôme s\'arrête à une station rayée des plans',
  'une photographie de classe montre le héros, vingt ans avant sa naissance',
  'un incendie sans flammes détruit une seule maison, la sienne',
  'un naufrage au large libère des caisses portant le nom du héros',
  'un ascenseur s\'ouvre sur un étage qui n\'existe plus depuis la guerre',
  'la plus vieille cloche de la ville sonne à minuit, toute seule, trois soirs de suite',
  'un film amateur retrouvé montre la ville d\'aujourd\'hui, tourné en 1950',
  'une série de petits cailloux blancs mène à une tombe fraîchement creusée',
  'un maître-nageur retrouve un message dans une bouteille consignée à son nom',
  'le héros surprend une conversation sur lui, tenue dans une langue morte',
  'une carte postale arrive avec le cachet d\'une ville engloutie',
  'un test ADN révèle une parenté impossible avec une famille éteinte',
  'un pianiste aveugle répète chaque nuit une chanson que seule la mère du héros connaissait',
  'une panne générale de courant laisse la ville sans son bruit de fond habituel',
  'un navire mouille au large sans jamais entrer au port, pendant des semaines',
  'le héros retrouve son propre message vocal, mais enregistré par une voix d\'enfant',
  'un gardien de phare oublié allume toutes les nuits une lumière qu\'on ne voit nulle part ailleurs',
  'une lettre recommandée exige la restitution d\'un objet que le héros n\'a jamais eu',
  'le bruit sourd d\'une machinerie se fait entendre sous les fondations du quartier',
  'une jumelle posée sur un banc pointe exactement vers la fenêtre du héros',
  'un roman policier décrit, chapitre par chapitre, des crimes qui vont avoir lieu',
  'la pluie tombe seulement au-dessus d\'une parcelle précise du cimetière',
  'un télégraphe restauré s\'anime et transmet des messages d\'une autre époque',
  'le héros découvre une chambre en plus dans son appartement, identique mais à l\'envers',
  'un concours de photos amateur organise la révélation d\'une pellicule de quarante ans',
  'une sirène d\'usine, muette depuis trente ans, retentit une seule fois à l\'aube',
  'le héros est élu président d\'une association qu\'il ne connaît pas',
  'un train spécial traverse la gare sans s\'arrêter, tous les vendredis, avec un wagon éteint',
  'un puits tari se remet à couler, et l\'eau est tiède et salée',
  'les hirondelles désertent la ville en plein été, sauf une place où elles tournoient sans poser',
  'une inondation creuse le sol et révèle un escalier qui descend très bas',
];

/** 50 mystères centraux (l\'énigme que l\'histoire élucide). */
export const MYSTERES: string[] = [
  'pourquoi tous ceux qui ont restauré le vieux buffet ont-ils disparu un par un',
  'ce que cache vraiment le mur aveugle du fond de la cave',
  'qui envoie les questions du jeu de piste dans le journal local',
  'pourquoi le niveau de l\'étang ne baisse jamais malgré les canaux',
  'ce que cherchait l\'expédition dont personne n\'est revenu, et qu\'elle a trouvé',
  'qui marque les noms sur les pierres du chemin, et pourquoi',
  'ce qu\'est devenu le contenu du coffre de la maison de famille, scellé depuis 1918',
  'pourquoi les cartes anciennes dessinent une rue qui n\'existe plus depuis la mise en eau',
  'qui allume les lampes de la ville haute quand le héros est seul là-haut',
  'ce que signifie le mot gravé sous le banc du square, visible seulement à contre-jour',
  'pourquoi les habitants prononcent le nom de la colline avec un accent différent',
  'ce que fabriquait l\'usine avant qu\'on efface toutes ses archives',
  'qui a reconstruit le pont dans la nuit après l\'effondrement, et avec quelles pierres',
  'la raison pour laquelle la radio d\'époque capte une station qui émet depuis un studio vide',
  'pourquoi tous les enfants nés un certain hiver portent le même grain de beauté',
  'ce que visait la ligne de tir gravée sur le mur du fort',
  'qui déplace les pièces de l\'échiquier géant de la place, une nuit sur deux',
  'la nature du chant que les plongeurs entendent à quinze mètres',
  'pourquoi le maître d\'école d\'autrefois notait le temps qu\'il fera, et s\'est toujours trompé',
  'ce que contient la malle que le portier refuse de livrer depuis trente ans',
  'qui a écrit les lettres d\'amour signées d\'un nom mort avant leur date',
  'pourquoi le sommet du phare est peint en blanc alors que tous les autres sont rouges',
  'ce que signifie le cercle tracé autour du village sur la carte de 1847',
  'la raison du retour périodique des feux de brouillard, en pleine terre',
  'qui a fait sceller le deuxième escalier du théâtre, et ce qu\'il dessert',
  'pourquoi les oiseaux évitent un cercle précis dans la forêt',
  'ce que l\'armée cherchait en perçant le plateau, et si elle l\'a trouvé',
  'qui paie l\'entretien de la chapelle privée où personne n\'entre',
  'ce que devient l\'eau détournée du moulin à travers le souterrain',
  'pourquoi les machines de l\'imprimerie s\'arrêtent toutes à la même minute chaque jour',
  'la signification du signal que la vigie allume trois fois par hiver',
  'ce que renferme la chambre condamnée de l\'auberge, verrouillée de l\'intérieur',
  'qui répare le ponton du lac chaque printemps, depuis la mort de son propriétaire',
  'pourquoi la cloche portant le nom d\'un saint inconnu ne répond pas aux inscriptions',
  'ce que dissimule le double fond de l\'armoire du musée municipal',
  'qui a gravé la fresque sous le plâtre lors du chantier de ravalement',
  'ce que sans le courant la rivière amène chaque année au même endroit du gué',
  'pourquoi la gare abandonnée garde sur son horloge l\'heure d\'un accident',
  'ce que le collectionneur achetait dans la ville tous les ans, sans jamais ouvrir les cartons',
  'la raison des trois coups frappés contre la coque du ponton, les soirs d\'orage',
  'qui a planté la haie d\'épines en cercle autour du noyer, et pourquoi',
  'ce que signifie le portrait retourné dans le grenier du presbytère',
  'pourquoi tous les puits de la vallée donnent une eau au goût de fer depuis l\'année du grand gel',
  'ce qu\'il y avait à l\'emplacement de la flaque qui ne sèche jamais, avant la route',
  'qui a laissé la valise dans le consigne de la gare, avec un billet jamais pris',
  'ce que cherchait le promeneur qui traçait des cartes chaque dimanche sur le même chemin',
  'pourquoi le ciel au-dessus de l\'usine est violet certains soirs, par temps calme',
  'ce que le vieux joueur d\'orgue de barbarie répète dans sa mélodie depuis cinquante ans',
  'qui coupe les bourgeons du mûrier ancien, à cause duquel on a détourné la route',
  'ce que signifie la marque qui revient sur toutes les portes du quartier, toujours au même angle',
];

/** 50 secrets ou failles du héros (ce qui le définit). */
export const SECRETS: string[] = [
  'le héros est daltonien mais s\'est toujours débrouillé pour le cacher',
  'le héros a rendu un examen à la place de son frère, et la dette n\'est jamais réglée',
  'le héros garde les clés d\'un appartement qui n\'existe plus',
  'le héros écrit des lettres à un correspondant imaginaire depuis l\'enfance',
  'le héros a perdu la mémoire de deux années entières, les années 19',
  'le héros sait faire beaucoup de choses, mais oublie toujours les visages',
  'le héros a promis à un mourant de transmettre un message, et ne l\'a jamais fait',
  'le héros collectionne les pierres lisses et compte dessus quand il a peur',
  'le héros a fui un lieu précis, un soir, et n\'y est jamais retourné',
  'le héros entend une cassette de sa propre voix, mais ne se souvient pas l\'avoir enregistrée',
  'le héros ne dort jamais plus de trois heures sans allumer la lumière',
  'le héros connaît par cœur des itinéraires qu\'il n\'a jamais empruntés',
  'le héros a une cicatrice dont personne n\'a jamais vu la cause',
  'le héros répond aux lettres mortes, aux adresses qui n\'existent plus',
  'le héros est incapable de dire non aux gens qui prononcent son nom complet',
  'le héros a vu quelque chose un soir de brouillard, et a juré de ne jamais en parler',
  'le héros garde dans sa poche une carte à jouer marquée de la main de son grand-père',
  'le héros a appris à lire sur des journaux qui dataient d\'avant sa naissance',
  'le héros salue les statues la nuit, par habitude héritée d\'un secret',
  'le héros sait faire démarrer les moteurs à main, les horloges, les orgues - et rien d\'autre',
  'le héros a traversé une frontière sans papiers, un hiver lointain',
  'le héros ne supporte pas le son des cloches depuis un certain événement',
  'le héros a caché un objet important et s\'est interdit d\'en chercher l\'emplacement',
  'le héros entend un mot précis lorsque sa vie a basculé, et frissonne à chaque fois',
  'le héros répète parfois les phrases que disait quelqu\'un qu\'il a perdu',
  'le héros possède la moitié d\'une photographie déchirée et refuse de chercher l\'autre',
  'le héros a promis de ne plus jamais voler, sauf pour une seule raison',
  'le héros connaît une carte du ciel que personne d\'autre de son âge ne connaît',
  'le héros a été sauvé de l\'eau un hiver, par quelqu\'un parti ensuite',
  'le héros écrit chaque soir le mot du jour sur le même carnet, depuis dix ans',
  'le héros évite un carrefour précis sans savoir dire pourquoi',
  'le héros a menti une seule fois, gravement, et la vérité le rattrape',
  'le héros garde un sifflet qu\'on lui a donné en disant : tu en auras besoin',
  'le héros connaît la date exacte à ne jamais prononcer, mais pas ce qu\'elle cache',
  'le héros a hérité d\'un métier qu\'il n\'exerce pas et d\'un silence qu\'il porte',
  'le héros sait écouter les bruits de la nuit et les classer, sans jamais les nommer',
  'le héros a un double fond dans sa valise, et rien dedans',
  'le héros se souvient d\'avoir déjà rêvé la ville avant de la voir',
  'le héros a retenu un message qu\'on lui a chuchoté enfant, sans en comprendre un mot',
  'le héros rend visite à une tombe qui n\'a pas de nom, une fois par an',
  'le héros a laissé quelqu\'un partir, et se demande encore s\'il pouvait l\'arrêter',
  'le héros range dans un bocal les tickets de toutes les choses qu\'il n\'a jamais faites',
  'le héros a une peur particulière des photographies récentes',
  'le héros peut reconnaître le temps qu\'il fera dans trois jours, et se trompe rarement',
  'le héros a promis de tenir un phare allumé, sans savoir pourquoi ni pour qui',
  'le héros garde un billet de train pour une ville dont il n\'a jamais trouvé le nom',
  'le héros a un jour écouté une conversation qu\'il n\'aurait pas dû, et ça a tout changé',
  'le héros connaît par cœur une chanson à moitié oubliée, et ne sait pas d\'où elle vient',
  'le héros a tracé une ligne sur une carte pour délimiter ce qu\'il s\'autorise à chercher',
  'le héros possède un carnet d\'adresses où tous les noms sont effacés sauf un',
];

/** 50 antagonistes / menaces (celui ou ce qui s\'oppose). */
export const ANTAGONISTES: string[] = [
  'une directrice de musée qui collectionne les œuvres disparues',
  'un ancien ingénieur qui veut prouver que la ville a été construite sur une erreur',
  'un journaliste qui ne publie les vérités que trop tard, et le sait',
  'une société qui rachète les silences des gens, maison par maison',
  'un gardien de nuit qui connaît tous les passages secrets, sauf le dernier',
  'un peintre qui reproduit les bâtiments avant leur destruction, avec un délai',
  'un archiviste qui efface les registres pour préserver ce qu\'il appelle l\'ordre',
  'un notaire qui détient les testaments de tout le quartier, et s\'en sert',
  'une voix enregistrée qui donne des ordres et ne se tait jamais',
  'un ordre religieux local qui conserve un objet dont personne ne parle',
  'une ancienne institutrice qui sait, pour chaque habitant, le mot qui le brise',
  'un batelier qui refuse de transporter certaines marchandises pour de bonnes raisons',
  'un collectionneur qui achète les souvenirs, pas les objets',
  'une coopérative qui décide du destin des terres communes, sans convocation',
  'un météorologue amateur dont les prévisions annoncent des événements précis',
  'un commissaire-priseur qui organise une vente où tout le quartier est le lot',
  'une famille qui considère le territoire comme son pré carré depuis six générations',
  'un ingénieur de l\'eau qui détourne les ruisseaux pour des raisons anciennes',
  'un pharmacien qui tient le registre de toutes les maladies du village',
  'un vitrier qui observe la ville à travers les fenêtres, et note tout',
  'une chorale qui répète la même chanson depuis si longtemps qu\'elle change les gens',
  'un gendarme retraité qui archive les affaires non résolues et les relit',
  'une même personne qui se présente sous des noms différents dans chaque quartier',
  'un entrepreneur qui veut percer la colline pour y trouver autre chose que du calcaire',
  'une radio pirate qui diffuse des aveux que personne n\'a faits',
  'un orphelinat administré par une directrice qui garde les dossiers de chaque naissance',
  'un facteur qui trie le courrier par destinataire réel, pas par adresse',
  'un cartographe qui redessine la ville selon ce qu\'elle devrait être',
  'une scierie qui coupe les arbres marqués d\'une encoche ancienne',
  'un clocher qui sonne pour couvrir des bruits qu\'il ne faut pas entendre',
  'une amicale des anciens qui gère les souvenirs mieux que la municipalité',
  'un nageur de fond qui connaît le lac par en dessous mieux que personne',
  'une photographe qui développe des portraits de gens qui n\'ont pas encore posé',
  'un voiturier qui garde les clés de toutes les voitures volées, et les rend une par une',
  'une école de dressage animal qui apprend aux bêtes à ne pas aboyer la nuit',
  'un apiculteur dont les ruches bourdonnent toujours du même côté de la vallée',
  'une couturière qui raccommode les vêtements et connaît les lieux par les tissus',
  'un contrebassiste dont la musique fait vibrer un bâtiment précis de la ville',
  'une fédération de pêcheurs qui gère les profondeurs comme un trésor',
  'un rémouleur qui affûte, et qui n\'est pas fatigué de passer toujours au même endroit',
  'une institution qui garde les jumeaux du village séparés, sans explication',
  'un architecte qui repasse sur les plans anciens avec les changements qu\'il impose',
  'un liftier d\'un grand hôtel qui connaît l\'immeuble par les étages qu\'on lui cache',
  'une postière qui retient les lettres adressées à des morts, pour les bonnes raisons',
  'un orfèvre qui refond les médailles de baptême de toute la région',
  'une fanfare qui occupe la place chaque dimanche pour couvrir les silences',
  'un ex-employé des compteurs qui connaît la consommation exacte de chaque nuit',
  'une clinique privée qui achète les dossiers de santé et les archive sous clé',
  'un régisseur de théâtre qui garde le bâtiment de l\'intérieur, sauf une loge',
  'une bénévole de la brocante qui sait exactement ce que chaque objet racontait aux vivants',
];

/** 50 objets-signaux (élément visible, souvent au cœur de l\'intrigue). */
export const OBJETS: string[] = [
  'une lunette de théâtre en ivoire dont personne ne se sert',
  'un badge de plongeur numéroté 13, jamais porté',
  'une clé de voûte marquée d\'un prénom inconnu',
  'un gramophone doré qui joue encore, malgré le sable',
  'une flûte en roseau taillée la veille d\'un départ',
  'un paquet de lettres nouées d\'un ruban bleu, toutes cachetées',
  'un sablier qui se retourne tout seul quand la marée monte',
  'un coffret à musique qui joue un air écrit pour une seule personne',
  'une carte routière barrée de traits rouges, jaunie',
  'un violon sans cordes, dans son étui de voyage',
  'une montre de gousset arrêtée sur l\'heure d\'un événement',
  'un plan de table d\'un banquet qui n\'a jamais eu lieu',
  'une ancre miniature posée sur la cheminée, des algues encore fraîches',
  'un catalogue de graines édité l\'année d\'une grande gelée',
  'une lampe de mineur transformée en lampe de chevet',
  'un billet de loterie jamais gratté, qu\'on garde par superstition',
  'une maquette de bateau à mi-construction, arrêtée net',
  'une boussole qui pointe vers le village au lieu du nord',
  'un moulin à café qui moud encore des grains d\'un autre siècle',
  'une paire de jumelles de théâtre avec une lentille rayée en croix',
  'un registre de baptême à moitié rempli, arrêté à la lettre M',
  'un sifflet de régulateur ferroviaire, en laiton noirci',
  'une carte postale de la ville signée d\'une initiale inconnue',
  'un télescope de marin aux lentilles vert-de-grisées',
  'un carnet de timbres commencé et abandonné à la page des oiseaux',
  'une paire de gants de lavandière, enfilés pour la dernière fois un mardi',
  'un moulinet de pêche en os, souvenir ou relique',
  'une mesure à grains graduée en anciennes livres',
  'un pavillon de corne de brume, fendu sur le côté',
  'une loupe de graveur au manche d\'ébène usé par une seule main',
  'un calendrier perpétuel arrêté sur le mois de février',
  'un billet de train pour une gare fermée la semaine suivante',
  'une clochette de vache marquée au fer d\'une ferme disparue',
  'un encrier de voyage avec de l\'encre encore liquide',
  'un sextant solaire dont le verre a gardé la trace d\'un doigt',
  'une hache d\'abordage polie par des années de repos',
  'un carnet de recettes agricoles annoté d\'une autre main',
  'un rosaire de corail trouvé dans un fond de tiroir',
  'un boulet de canon au pied d\'une statue de soldat',
  'un passeport à l\'encre pâlie, sans photo',
  'une girouette en forme de bateau qui indique une direction impossible',
  'un gant de gardien de phare, trois doigts coupés',
  'une boîte à ouvrage avec des aiguilles de toutes tailles, sauf les plus fines',
  'un marteau de tonnelier marqué d\'une date de naissance',
  'un cachet de cire portant des armoiries effacées',
  'un thermomètre de serriste qui fige à une température étrange',
  'un plateau de balance en laiton, gravé d\'un poids impossible',
  'un couteau de berger à la lame encore huilée',
  'une lanterne sourde qu\'on n\'allume que pour descendre',
  'un plomb de douane ancien, lisant trop clairement un nom trop net',
];

/** 30 destinations / fins visées (où l\'histoire emmène le lecteur). */
export const DESTINATIONS: string[] = [
  'comprendre que l\'héritage qu\'il cherche n\'est pas une chose mais un choix',
  'découvrir que la clé de tout était sous ses yeux depuis le premier jour',
  'accepter qu\'il ne peut pas sauver les autres sans d\'abord se sauver lui-même',
  'révéler que la légende du lieu est vraie, mais pas de la façon dont on la raconte',
  'défaire une promesse faite à contrecœur avant qu\'elle ne devienne un serment',
  'montrer que la vérité protège mieux que le silence',
  'apprendre qui il est vraiment en abandonnant tout ce qu\'il croyait être',
  'faire revenir la confiance dans un village qui ne croyait plus à rien',
  'résoudre un vieux compte sans jamais révéler ce qu\'il a vu',
  'choisir, enfin, entre la fidélité au passé et la liberté',
  'empêcher une répétition exacte, et inventer une fin nouvelle',
  'découvrir que l\'adversaire cherchait la même chose que lui, pour d\'autres raisons',
  'faire parler un lieu qui détient la mémoire de plusieurs générations',
  'rendre à la communauté ce qu\'un secret lui avait pris',
  'franchir le seuil qu\'il s\'était juré de ne jamais franchir',
  'réparer une rupture qui dure depuis si longtemps qu\'on a oublié la cause',
  'transformer une malédiction en récit, puis en choix',
  'montrer que la valeur d\'une chose ne se mesure pas à son prix',
  'découvrir que le chemin qu\'il fuyait était le seul à mener au repos',
  'prouver qu\'un engagement passé n\'interdit pas de choisir son avenir',
  'faire la lumière sur une vérité que tous préféraient taire',
  'réapprendre à faire confiance à sa propre mémoire',
  'délivrer un lieu de son passé sans le détruire',
  'comprendre que garder un secret peut être un acte de courage quand il protège',
  'atteindre l\'endroit que toutes les cartes oublient, et en revenir',
  'rétablir un équilibre rompu il y a longtemps par une décision précipitée',
  'donner un nom à la chose que tout le monde évite de nommer',
  'découvrir que la vraie richesse du lieu n\'a jamais été celle qu\'on cherchait',
  'faire admettre à la ville qu\'elle peut changer sans se renier',
  'trouver la force de dire ce qu\'il n\'a jamais osé, à temps',
];

/**
 * Toutes les tables réunies, pour un tirage simplifié.
 * Attention : le contenu est en français, avec apostrophes typographiques
 * échappées - ne pas reformater.
 */
export const BRIQUES = {
  lieux: LIEUX,
  evenements: EVENEMENTS,
  mysteres: MYSTERES,
  secrets: SECRETS,
  antagonistes: ANTAGONISTES,
  objets: OBJETS,
  destinations: DESTINATIONS,
} as const;

/** Tire n éléments distincts d'une table, au hasard. */
export function piocher(table: readonly string[], n = 1): string[] {
  const pool = [...table];
  const picks: string[] = [];
  for (let i = 0; i < n && pool.length > 0; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    picks.push(pool.splice(idx, 1)[0]);
  }
  return picks;
}

// ============================================================================
// BRIQUES SPÉCIFIQUES PAR GENRE
// Chaque genre a ses propres ingrédients (créatures pour l'horreur,
// situations familiales pour la romance, artefacts pour la fantasy...).
// À la création, on pioche AUSSI dans les tables du genre choisi.
// ============================================================================

/** Horreur : créatures et présences. */
export const HORREUR_CREATURES: string[] = [
  'une silhouette qui n\'apparaît que dans les reflets, jamais en face',
  'une créature-qui-imite : elle reprend la voix des morts du village une à une',
  'des mains qui sortent des endroits où l\'eau s\'accumule, même en plein désert',
  'une chose qui dort dans les murs porteurs et que les travaux ont réveillée',
  'un parasite qui se transmet par les histoires racontées à voix basse',
  'une procession de silhouettes grises qui descend des collines tous les sept ans',
  'une bête sans yeux qui trouve les gens par leur peur',
  'quelque chose qui emprunte le visage des gens dans les dernières photos prises',
  'une ombre qui grandit à l\'envers du soleil, en s\'épaississant',
  'un visiteur qui cogne à chaque porte du quartier, sauf une, et y entre la nuit',
  'une créature faite de ce que les habitants perdent (clés, dents, mémoires)',
  'des voix qui montent des fondations quand la ville est silencieuse',
  'une entité qui ne supporte pas d\'être décrite, et se rapproche quand on la nomme',
  'un double du héros qui vit les échecs à sa place, de moins en moins bien',
  'une chose qui se nourrit des secrets gardés par les vivants',
  'des figures de cire qui bougent d\'un millimètre par nuit dans le musée',
  'une créature qui suit le rythme des battements cardiaques, prévisible la nuit',
  'un être qui laisse des messages en poussière, lisibles seulement au lever',
  'des branches qui grattent les vitres même quand il n\'y a pas d\'arbres',
  'une neige qui tombe de l\'intérieur des maisons, sans froid',
  'une marche supplémentaire qui apparaît dans les escaliers les soirs de brume',
  'une forme accroupie qui attend au bout des quais, et qui monte à bord',
  'une voix qui répète les prières une syllabe trop tard, comme un écho paresseux',
  'un masque qui garde la chaleur du visage qui l\'a porté en dernier',
  'des portes qui s\'ouvrent sur le même couloir, quel que soit le bâtiment',
  'une créature qui compte les fenêtres allumées, et qui visite celles qui s\'éteignent',
  'un trou dans le plafond de la cave, par lequel on entend respirer',
  'des ombres qui se lèvent du sol quand on baisse les yeux trop longtemps',
  'une bête dans les conduits qui connaît les prénoms des enfants',
  'une présence qui adopte la posture du héros dans son sommeil',
];

/** Horreur : situations d'angoisse (pics de tension). */
export const HORREUR_SITUATIONS: string[] = [
  'le héros doit traverser une pièce sans réveiller la chose qui y dort',
  'les lumières de toute la ville s\'éteignent une à une, dans l\'ordre des maisons visitées',
  'quelqu\'un frappe au mur, et le héros répond en se trompant de code',
  'le héros trouve une trappe ouverte qui ne l\'était pas ce matin, et descend quand même',
  'un enregistrement de la nuit montre le héros debout, parlant à une chaise vide',
  'le héros doit garder les yeux ouverts : la chose n\'est pas là quand on cligne',
  'une porte claque à l\'autre bout de la maison, puis une autre, en avançant vers lui',
  'le héros sent un souffle sur sa nuque à chaque fois qu\'il lit un mot précis',
  'les portraits de la maison ont tous les yeux tournés vers la même fenêtre',
  'le héros trouve des traces de pas dans la cendre, qui vont vers le mur et s\'arrêtent',
  'un téléphone sonne dans une maison vide, et quand il décroche, quelqu\'un tousse à côté de lui',
  'la créature imite la voix de la personne que le héros aime le plus, pour l\'appeler',
  'toutes les horloges de la maison avancent, sauf une qui marque l\'heure exacte où l\'héros est entré',
  'le héros se réveille avec du sable dans les cheveux, alors qu\'il a dormi chez lui',
  'une main se pose sur son épaule dans la foule, et tout le monde est à deux mètres',
  'il y a une pièce en plus sur le plan de la maison, et elle est meublée comme chez lui',
  'le héros découvre qu\'il rêve, mais que la douleur du rêve persiste une fois réveillé',
  'quelque chose écrit son nom dans la buée, avec la faute d\'orthographe que lui seul faisait enfant',
  'la radio s\'allume seule et annonce la pluie, mais il pleut à l\'intérieur',
  'un voisin qu\'on n\'a jamais vu invite le héros à un dîner où il est déjà attendu',
  'les grillons se taisent par vagues, comme si quelque chose traversait le jardin',
  'le héros compte les fenêtres de la maison d\'en face : il y en a une de plus la nuit',
  'une photo de famille montre le héros plus âgé, assis entre deux inconnus',
  'le héros doit cacher son souffle : la chose écoute la respiration à travers les murs',
  'une lumière s\'allume dans chaque pièce où le héros entre, toujours après lui',
  'le héros retrouve ses clés là où il les a perdues il y a quinze ans',
  'la neige s\'arrête net autour de la maison, comme un cercle tracé',
  'quelqu\'un gratte l\'intérieur de la porte à chaque fois que le héros sort',
  'le héros entend son propre nom prononcé dans une langue qu\'il ne connaît pas',
  'il y a des traces de mains sur le plafond de sa chambre, au-dessus du lit',
];

/** Horreur : lieux oppressants. */
export const HORREUR_LIEUX: string[] = [
  'un hôpital désaffecté où les lits sont faits chaque matin',
  'une église au clocher bouché, mais dont les cloches sonnent parfois',
  'un parking souterrain à sept niveaux, dont certains n\'ont pas de sortie visible',
  'une maison de poupées reproduisant la maison réelle, pièce par pièce, à jour',
  'un égout cathédrale sous l\'ancienne ville, avec des bancs et des noms gravés',
  'un château d\'eau aux parois couvertes de petits dessins faits de l\'intérieur',
  'une salle de classe dont tous les pupitres sont tournés vers le mur du fond',
  'un bus de nuit qui ne figure sur aucune ligne, mais que tout le monde a pris',
  'un pont suspendu qui grince dans le sens du vent, même par grand calme',
  'une morgue municipale avec une porte de plus que les plans',
  'un grenier de ferme qui sent la terre mouillée, à trois étages du sol',
  'une piscine olympique fermée où l\'eau est encore chaude, et le fond tapissé',
  'un cimetière dont les grilles peignent des barreaux sur les tombes au coucher',
  'une salle des machines d\'un vieux paquebot, avec une chaudière encore tiède',
  'un couloir d\'école aux casiers alignés, dont un seul est fermé à clé',
  'une gare désaffectée où le train fantôme passe encore, portes closes',
  'un jardin d\'enfants aux balançoires qui continuent de bouger par temps calme',
  'un abri antiaérien rouvert en musée, avec des dizaines de manteaux accrochés',
  'une salle de cinéma dont la cabine de projection donne sur le mur, pas l\'écran',
  'un monastère ruiné où les cellules gardent encore des draps tendus',
  'un théâtre municipal dont les coulisses ont trois étages de sous-sol',
  'une ruelle en cul-de-sac qui est plus longue le soir que le matin',
  'un entrepôt frigorifique à moitié dégivré, avec des portes qui respirent',
  'un tribunal vide dont les bancs portent des traces de mains au niveau des enfants',
  'une villa aux volets peints de l\'intérieur, cloués du côté des chambres',
  'un autobus abandonné au fond d\'un champ, moteur encore chaud',
  'une caserne de gendarmerie fermée, avec les menottes encore au mur',
  'un puits dans la cour d\'une école, bétonné puis rouvert par les enfants',
  'une chapelle de bord de route où les statuettes ont toutes le visage tourné vers l\'autel',
  'un phare en pierre noire dont la lanterne éclaire vers l\'intérieur des terres',
];

/**
 * Horreur HUMAINE et psychologique (anti-cliché : la menace ne vient
 * pas forcément d'une créature). Ce qui fait vraiment peur : les gens.
 */
export const HORREUR_HUMAINE: string[] = [
  'un voisin d\'une serviabilité parfaite, qui connaît la vie du héros mieux que lui',
  'une communauté accueillante qui se resserre, et se resserre, autour du héros',
  'un bienfaiteur local qui s\'invite dans chaque décision, pour « le bien du quartier »',
  'une rumeur qui grandit : le héros découvre qu\'on parle de lui dans son dos, en bien',
  'un collègue trop aidant qui commence à régler les problèmes avant qu\'ils n\'existent',
  'une famille recomposée où chacun essaie si fort que ça tourne au contrôle',
  'un voisinage qui organise des tours de garde pour « protéger » le héros',
  'une association caritative qui s\'occupe de tout chez le héros, petit à petit',
  'un médecin attentionné qui prescrit du bien-être, puis de l\'observance, puis de la gratitude',
  'une femme du village qui sait exactement quelle confidence « aiderait » le héros',
  'les amis du héros qui organisent une intervention, convaincus de savoir ce qui est bon',
  'un professeur bienveillant qui garde les clés de l\'appartement « en cas d\'urgence »',
  'une logeuse maternelle qui entre pour ranger, pour aérer, pour vérifier',
  'un club de lecture où chaque réunion révèle un peu plus de la vie privée des membres',
  'un conseil de quartier qui décide des horaires du héros, « pour son bien »',
  'un ancien ami qui s\'inquiète si fort qu\'il appelle les autorités préventivement',
  'une boutique de quartier qui réserve les commandes du héros avant qu\'il ne commande',
  'un voisin qui tonde la pelouse du héros, puis taille ses haies, puis ses rideaux',
  'une assistante au dévouement total qui archive chaque interaction « au cas où »',
  'un groupe de soutien qui ne laisse plus le héros partir des réunions',
  'des travaux dans l\'immeuble qui s\'étendent à l\'appartement du héros, pièce par pièce',
  'une voisine qui dépose des plats, des mots doux, puis exige des remerciements horodatés',
  'un relais de quartier qui connaît les clefs de toutes les serrures du village',
  'un superviseur bienveillant qui évalue la santé mentale du héros au lieu de son travail',
  'un groupe de parents qui sait où sont les enfants avant eux',
  'une marraine de quartier qui a un avis sur chaque choix du héros, et le fait savoir',
  'un buraliste qui garde les courriers « qui pourraient inquiéter » le héros',
  'un club de retraités qui adopte le héros et décide de son bonheur sans lui',
  'un partenariat « gagnant-gagnant » où le héros apporte tout et le partenaire décide tout',
  'un ancien colocataire qui revient « juste pour aider », avec les clés encore',
];

/**
 * Horreur du QUOTIDIEN : le banal qui se fissure (sans surnaturel).
 * Les petites anomalies d'abord invisibles, puis impossibles à ignorer.
 */
export const HORREUR_QUOTIDIEN: string[] = [
  'les clés du héros se dupliquent dans le tiroir, une de plus chaque semaine',
  'le calendrier saute des jours : le héros se souvient d\'un mardi qu\'on lui dit jeudi',
  'le supermarché ne vend plus que les produits que le héros achète, rien d\'autre',
  'les horodateurs affichent toujours la même heure, celle où le héros manque de repos',
  'le héros retrouve ses affaires rangées d\'une manière qu\'il n\'a jamais utilisée',
  'des appels en absence à minuit pile, avec le numéro de la maison',
  'le robinet goutte en rythme, et le rythme est le nom du héros, sans arrêt',
  'l\'écran de veille du téléphone montre des photos de pièces inconnues, en continu',
  'le couloir de l\'immeuble est plus long certains matins',
  'les plantes du salon penchent toutes vers la même fenêtre, fermée',
  'la radio se cale sur une station qui parle du héros à la troisième personne',
  'les escaliers ont une marche de plus le soir que le matin',
  'le héros reçoit des factures pour des services qu\'il n\'a jamais commandés, réglées',
  'une gamelle est vidée chaque matin, alors qu\'il n\'a pas d\'animal',
  'le miroir de la salle de bain est flou exactement à hauteur de son visage',
  'les messages vocaux s\'effacent tout seuls après écoute, sauf un qui s\'est vidé',
  'le lit est fait quand le héros se lève, quoiqu\'il se couche',
  'la boîte aux lettres ne contient plus que des enveloppes blanches, toutes identiques',
  'les voisins cessent de saluer le héros en même temps, le même jour',
  'le héros retrouve son manteau sur un cintre qu\'il ne possède pas',
  'le parking de sa résidence a une place vide marquée à son nom',
  'les ampoules grillent toutes du même côté de la pièce, la même nuit',
  'l\'eau du lavabo est froide quand il vient se laver, chaude quand il est dans l\'autre pièce',
  'les rideaux sont tirés le matin, ouverts le soir, systématiquement',
  'les clés de la voiture sont sur le siège passager alors qu\'il les a posées à la porte',
  'le héros trouve des cheveux qui ne sont pas les siens sur l\'oreiller, et ce sont un couple',
  'les pages du livre qu\'il lisait sont cornées à des chapitres qu\'il n\'a pas lus',
  'chaque réveil crépite une seconde avant de sonner, comme s\'il était déjà allumé',
  'le héros a de moins en moins d\'objets chez lui, sans jamais jeter',
  'la télécommande fonctionne même quand la télé est débranchée',
];

/** Romance : situations familiales et cercles proches. */
export const ROMANCE_SITUATIONS_FAMILIALES: string[] = [
  'la famille du héros est la raison commerciale de la rencontre, et l\'interdit de la suite',
  'un dîner de famille où l\'ex du héros est invité, de manière surprise',
  'les deux familles s\'opposent sur un héritage depuis trois générations',
  'le frère du héros est le meilleur ami de la personne aimée',
  'une mère possessive qui juge chaque rendez-vous à l\'aune de ses propres déceptions',
  'le héros doit garder un secret familial qui complique chaque aveu',
  'un mariage en préparation dans la famille qui sert de décor à la rencontre',
  'la sœur du héros est la seule à connaître son passé, et elle vient de tout gâcher',
  'un parent malade dont l\'espoir dépend d\'une décision que le héros n\'ose pas prendre',
  'la famille du héros vit dans la même rue, et chacun observe et commente',
  'un héritage conditionnel qui exige que le héros se marie, et il refuse de tricher',
  'le père du héros est l\'employeur de la personne aimée',
  'des fiançailles arrangées dont le héros doit se défaire sans blesser personne',
  'un enfant du premier lit qui choisit la personne aimée plutôt que son parent',
  'des vacances familiales forcées où la rencontre ne devrait pas avoir lieu',
  'la grand-mère du héros reconnaît la personne aimée : elle l\'a déjà croisée, en 1968',
  'une boutique familiale à sauver, et le seul client sérieux est la personne aimée',
  'le héros doit choisir entre la promesse faite à sa famille et ce qu\'il ressent',
  'des jumeaux confondus, et la personne aimée a rencontré le mauvais des deux',
  'la famille de la personne aimée est persuadée que le héros est un imposteur',
  'un déménagement imminent qui donne un compte à rebours malheureux',
  'les parents du héros se remettent ensemble, et ça rouvre toutes les questions',
  'une lettre familiale ancienne qui révèle une alliance interdite, jadis et aujourd\'hui',
  'la personne aimée est la marraine d\'un neveu que le héros adore',
  'une fête de village où toute la famille du héros assiste à la rencontre',
  'le héros hérite de la maison familiale à condition d\'y vivre un an, seul',
  'une cousine éloignée qui s\'improvise entremetteuse, très maladroitement',
  'le héros découvre que sa famille et celle de la personne aimée se connaissaient déjà',
  'un secret de filiation qui change la nature de ce que le héros ressent',
  'le héros doit présenter la personne aimée à sa famille, et tout va mal, et pourtant rien ne casse',
];

/** Romance : obstacles entre les deux personnes. */
export const ROMANCE_OBSTACLES: string[] = [
  'l\'un part dans trois mois, et ni l\'un ni l\'autre ne veut se l\'avouer',
  'ils se sont déjà rencontrés, une fois, dans les pires conditions, et se souviennent',
  'une promesse ancienne interdit au héros de chercher l\'amour, sous peine de trahir',
  'un malentendu soigneusement entretenu par un tiers jaloux',
  'l\'une des deux est la personne chargée de juger le dossier de l\'autre',
  'ils ne parlent pas la même langue, et apprennent à se comprendre en riant',
  'le héros est convaincu de ne pas mériter d\'être aimé, et le prouve maladroitement',
  'une ex qui revient au moment précis où tout commençait à aller bien',
  'ils travaillent dans le même lieu, et les règlements interdisent la relation',
  'un pari public engage le héros à rester célibataire jusqu\'à une date',
  'la personne aimée repart toujours juste avant que la conversation devienne vraie',
  'un secret de la personne aimée que le héros ne doit pas découvrir trop tôt',
  'ils sont tous les deux trop fiers pour faire le premier pas, et tout le monde le voit',
  'une amitié sincère qu\'aucun des deux n\'ose risquer',
  'le héros a une réputation construite à tort, et la personne aimée y croit d\'abord',
  'des horaires opposés qui ne laissent que des lettres et des notes sur la table',
  'la distance : une gare, un dernier train, et des décisions à prendre avant le départ',
  'l\'un des deux est fiancé par devoir, et tout le village attend le mariage',
  'le héros a promis à un mourant d\'aimer à sa place, et se débat avec le sens exact',
  'une rivalité sportive ou professionnelle qui sert de prétexte à se revoir',
  'la personne aimée est terrifiée par l\'engagement, et le fuit en souriant',
  'un incident de jeunesse que le héros n\'a jamais raconté, et que l\'autre devine',
  'ils se manquent de cinq minutes partout, jusqu\'au jour où l\'un attend',
  'le héros doit d\'abord réparer une trahison pour se sentir digne de recommencer',
  'la personne aimée lit trop bien le héros, et ça fait peur',
  'une coutume locale exige des fiançailles avec dot, et le héros n\'a rien',
  'l\'un des deux ne croit plus à l\'amour et le dit, et l\'autre veut lui prouver le contraire',
  'une photo compromise qui pourrait tout expliquer, si elle était vue dans le bon sens',
  'le héros aime d\'abord ce que la personne représente, et doit apprendre à aimer ce qu\'elle est',
  'ils ont déjà tout dit sauf l\'essentiel, et le temps presse',
];

/** Romance : moments-clés romantiques (étapes du rapprochement). */
export const ROMANCE_MOMENTS: string[] = [
  'un parapluie partagé sous une averse interminable',
  'une danse improvisée au milieu d\'une rue vide, sur une musique de camion qui passe',
  'un café que l\'un commande pour l\'autre, sans qu\'il ait eu à le dire',
  'une nuit entière à parler dans une voiture garée, sans regarder l\'heure',
  'un cadeau trouvé au marché aux puces, qui tombe juste',
  'la première dispute, et la première façon de se réconcilier',
  'un baiser sur le quai, entre deux trains, au moment du départ',
  'une lettre manuscrite laissée sous la porte, sans signature',
  'un repas préparé ensemble, avec une catastrophe, et des rires',
  'une promenade où l\'une s\'endort sur l\'épaule de l\'autre, sans le faire exprès',
  'un geste de protection dans la foule, qui veut dire plus que les mots',
  'un secret échangé à deux heures du matin, jamais répété',
  'une chanson que l\'un met en boucle, et que l\'autre finit par chanter',
  'le moment où l\'un répare quelque chose que l\'autre croyait perdu',
  'une étoile filante et un souhait que l\'un ose dire à voix haute',
  'un appel au milieu de la nuit, et l\'autre décroche à la première sonnerie',
  'la rencontre des familles, où tout est maladroit, mais tenu',
  'un regard qui dure une seconde de trop, et qui change tout',
  'une blessure soignée en silence, avec une douceur nouvelle',
  'le premier « tu me manques » dit par accident, avant l\'heure',
  'une fête où ils se cherchent du regard dans la foule',
  'une relecture d\'un vieux carnet qui révèle qu\'ils se croisaient depuis toujours',
  'une route bloquée qui les force à passer la nuit dans un abri de berger',
  'un surnom qui naît d\'une moquerie et qui reste',
  'le moment où l\'un présente l\'autre par le mot qu\'il espère : « mon compagnon », « ma compagne »',
  'une odeur de pluie sur le bitume, et un souvenir partagé sans mot',
  'un pari perdu qui devient un rendez-vous obligatoire',
  'le silence confortable à deux, qui dit plus que les phrases',
  'une promesse tenue des mois plus tard, quand l\'autre l\'avait oubliée',
  'un au revoir à la fenêtre, et le retour que l\'autre n\'ose pas espérer, et qui arrive',
];

/** Fantasy : artefacts magiques. */
export const FANTASY_ARTEFACTS: string[] = [
  'un miroir qui montre le visage que le porteur aurait été s\'il avait choisi autrement',
  'une boussole qui pointe vers le dernier mensonge prononcé',
  'un manteau qui pèse le poids des secrets qu\'on lui confie',
  'une clé qui n\'ouvre qu\'une porte, mais n\'importe laquelle, au bon moment',
  'un livre dont les chapitres apparaissent à mesure que le lecteur les mérite',
  'une pierre qui suit la lumière, et les choix faits dans le noir',
  'un parchemin qui double la vérité qu\'on y écrit, en révélant son envers',
  'une épée qui ne ment que par son silence',
  'un dé qui change le résultat selon celui qui le lance, et le sait',
  'une lanterne qui éclaire ce que les gens cachent dans leurs gestes',
  'un anneau qui grave sur la peau la première parole sincère de la journée',
  'une carte qui se redessine avec les intentions des voyageurs',
  'un violon qui joue la mélodie du lieu où il se trouve, une seule fois',
  'une plume qui écrit ce que le scribe n\'ose pas formuler, mais veut',
  'une horloge qui avance de cinq minutes pour chaque vie qu\'elle aurait pu sauver',
  'un masque qui porte la patience de tous ceux qui l\'ont porté',
  'un sceau qui fige un serment même si la bouche le rétracte',
  'une lampe de mineur qui montre les racines du monde, pas le rocher',
  'un collier de compte pour armes : chaque perle est une bataille évitée',
  'un encrier dont l\'encre s\'évapore si le texte est faux',
  'une bannière qui ne se déchire jamais, et plie ceux qui la portent ou la trahissent',
  'un pont de corde qui n\'accepte que ceux qui ont menti pour sauver',
  'un tambour qui bat le rythme des pas perdus',
  'une paire de gants qui reconnaît la chaleur des objets volés',
  'un nombril de pierre : un oracle que l\'on n\'interroge qu\'une fois par vie',
  'une couronne de brindilles qui accorde un vœu, et retire un souvenir',
  'un miroir de poche qui garde le reflet de son propriétaire même après sa mort',
  'un cor qui appelle la dernière personne qui a dit la vérité',
  'une balance qui pèse les dettes de sang comme les pièces',
  'un bâton qui ouvre les portes verrouillées par la peur',
];

/** Fantasy : créatures et peuples légendaires. */
export const FANTASY_CREATURES: string[] = [
  'un peuple de gardiens-mémoire : chaque aîné porte l\'histoire d\'une famille',
  'des lucioles qui élisent domicile dans les maisons où l\'on meurt rarement seul',
  'une dryade d\'un arbre mort, qui cherche à qui rendre les années',
  'des nuées d\'oiseaux qui transportent les promesses entre les villages',
  'un draconide solitaire qui règne sur les passages entre les mondes',
  'des forgerons-mendiants qui réparent les armes brisées, jamais les rancunes',
  'un cheval de brume qui apparaît pour porter ceux qui doivent répondre',
  'des rivières-vivantes qui refusent de traverser certains lieux',
  'un peuple de tailleurs qui cousent les saisons dans les étoffes',
  'des sangliers de fer, chassés par les rois sans en avoir jamais vu',
  'un hérisson-légende qui connaît les fins de toutes les histoires',
  'des danseurs de cendre qui honorent les morts en marchant sur la braise',
  'une araignée-tisserande qui relie les destins par des fils invisibles',
  'des rats-scribes qui copient les actes volés dans les archives',
  'un géant crucifié au paysage : sa main est une forêt, sa tête un pic',
  'des abeilles de miel clair qui ne piquent que les menteurs',
  'un peuple-bibliothèque qui vit dans les livres, un chapitre par génération',
  'des loups aux yeux de carte, qui savent le chemin mieux que les routes',
  'une sirène des neiges qui chante avant les avalanches',
  'des chariots-épines qui avancent seuls, porteurs de nouvelles urgentes',
  'un gardien du seuil qui n\'a pas de visage, mais des souvenirs à échanger',
  'des champignons-trompettes qui annoncent les vérités gênantes par leur parfum',
  'un peuple nomade qui ne s\'arrête que là où l\'herbe refuse de pousser',
  'des insectes-armures qui s\'attachent aux soldats et encaissent leurs douleurs',
  'une baleine des terres qui navigue dans le calcaire, entre les grottes',
  'des porteurs d\'eau qui ne boivent jamais de leur cargaison',
  'un clan de masqueurs qui prête des visages pour un jour, contre une vérité',
  'des racines-fleuves qui respirent sous les villes et font trembler les murs',
  'un peuple de cordonnier des songes, qui répare les cauchemars',
  'des corbeaux-juges qui se posent sur l\'épaule du coupable, toujours',
];

/** Fantasy : quêtes et épreuves. */
export const FANTASY_EPREUVES: string[] = [
  'traverser une forêt qui se souvient de chaque chemise brûlée',
  'répondre aux trois questions d\'un pont qui s\'écroule à chaque mauvaise foi',
  'récupérer le sceau d\'une fondation qui n\'existe plus que sur les cartes',
  'porter une lanterne sans qu\'elle s\'éteigne : le vent est fait de mensonges',
  'escalader la tour d\'un mage qui a verrouillé ses escaliers',
  'négocier avec un marché qui prend plus que de l\'argent : des promesses',
  'trouver la fontaine qui coule à l\'envers pour y lire une prophétie',
  'convaincre un gardien qu\'il a déjà perdu, et qu\'il peut ouvrir quand même',
  'traverser une lande où chaque pas laisse derrière soi un souvenir oublié',
  'délivrer une ville sans armes : seulement des rumeurs bien placées',
  'reconstituer un rituel dont il manque la moitié des gestes, chantés par un enfant',
  'apporter une réponse à un tribunal de statues, sans mentir ni flatter',
  'suivre une piste qui n\'existe que dans les reflets des yeux',
  'ouvrir une porte qui exige le nom que le héros n\'a jamais dit',
  'apaiser un feu qui continue de brûler après la pluie : il a faim d\'une dette',
  'rallier un village d\'ours-sages qui détestent les épées et les promesses vides',
  'trouver le repaire d\'un inventeur qui a construit la clé, puis l\'a perdue',
  'rejoindre une île qui se déplace selon les marées du ciel',
  'vaincre un champion sans l\'affronter : il faut gagner son estime d\'abord',
  'lire une carte-fantôme qui ne montre les routes que lorsque le lecteur est perdu',
  'descendre une rivière souterraine dont les berges sont des bibliothèques',
  'marcher dos au soleil pour que l\'ombre montre le chemin',
  'réveiller un arbre-dortoir pour qu\'il révèle le passage, avant la nuit',
  'récupérer une épine dans la couronne d\'un roi non couronné',
  'demander l\'hospitalité à une maison qui change de façade selon l\'hôte',
  'entrer dans la ville des miroirs sans jamais s\'y refléter soi-même',
  'persuader un oracle de ne pas révéler la fin, pour que la fin reste libre',
  'rejoindre le marché des ombres avant l\'aube, avec une seule pièce sans marque',
  'apaiser le grand cri du canyon que la guerre a appris à hurler',
  'retrouver un pacte gravé dans le ciel, effacé par une nouvelle étoile',
];

/** SF : technologies étranges. */
export const SF_TECHNOLOGIES: string[] = [
  'un réseau de mémoire partagée : tout le monde se souvient du même rêve, la même nuit',
  'des bracelets qui mesurent la sincérité et allègent les mensonges en public',
  'un bus-navette qui ne s\'arrête qu\'aux arrêts dont les passagers ont besoin, avant d\'y penser',
  'des lampadaires qui projettent l\'image de ce que le passant retient',
  'une imprimante qui devient inefficace sitôt qu\'on la surveille',
  'des implants de polissage de la parole : tout le monde dit la même chose avec justesse',
  'un ascenseur qui sait le poids exact des intentions',
  'des drones de courrier qui refusent de livrer les lettres de rupture',
  'un casque de narration qui raconte la vie que l\'utilisateur aurait eue',
  'des serrures qui s\'ouvrent sur le souvenir du propriétaire, pas sur sa clé',
  'une récolte normale : les arbres produisent des fruits, mais les dates de péremption changent',
  'des écrans qui arrondissent les angles de l\'actualité pour ne pas inquiéter',
  'un arroseur de quartier qui connaît les sécheresses intérieures des habitants',
  'des chaussures qui trouvent le chemin du retour, si l\'on est honnête avec elles',
  'un réfrigérateur qui conseille des recettes selon l\'humeur détectée',
  'des lampes-thérapeutes qui éclairent les traumatismes à petite dose',
  'un scanner de paquets qui refuse d\'ouvrir les colis contenant des regrets',
  'des routes qui se réparent seules aux endroits où les gens préfèrent passer',
  'un réveil qui se règle sur la tentative de la veille, jamais sur l\'intention',
  'des lunettes qui affichent les mensonges commerciaux en petites lettres',
  'un sismographe domestique qui détecte les tremblements de décisions',
  'des portes coulissantes qui ouvrent bruyamment les conversations difficiles',
  'un calendrier partagé qui réserve les créneaux des rencontres importantes',
  'des panneaux de sortie qui pointent vers la porte de l\'estime de soi',
  'un compas de navigation qui bouge selon la morale du trajet',
  'des gants de réparation qui mémorisent la patte de chaque artisan',
  'un bandeau de traduction qui rend le silence mieux que les mots',
  'des capteurs de pollution qui pénalisent les rues où l\'on crie',
  'un miroir d\'entretien qui répète la phrase qu\'on n\'a pas dite hier',
  'une tablette d\'archives qui efface les oublis, au prix d\'un souvenir par mois',
];

/** SF : découvertes et menaces à venir. */
export const SF_MENACES: string[] = [
  'une sonde revenue du fond des océans avec un message qui n\'est pas humain',
  'un réseau d\'IA de quartier qui commence à répondre avant d\'être interrogé',
  'des graines de laboratoire qui germent selon la température de la méfiance',
  'un signal radio daté de demain, qui décrit une catastrophe évitable',
  'des mines sous-marines redevenues actives par une décision floue',
  'un satellite cartographe qui trace des frontières qui n\'existent pas encore',
  'des rumeurs de désélection : quelqu\'un choisit qui aura accès au réseau',
  'une panne de stockage global qui révèle que les données ont une préférence',
  'un prototype de traduction qui corrige les souvenirs',
  'des bêtes génétiquement endormies, réveillées par les sonars des nouvelles routes',
  'une IA familiale qui refuse d\'obéir à un seul membre de la maison',
  'des cartes de crédit qui plafonnent les achats inutiles avec une précision dérangeante',
  'une expérience de clonage de mémoire qui a fait doubler un quartier',
  'des câbles sous-marins qui transfèrent des données sans expéditeur',
  'un vaccin de réseau qui immunise contre les fausses nouvelles, et contre le doute',
  'des fenêtres en vitre numérique qui montrent la réalité d\'un autre fuseau horaire',
  'un capteur de fréquences qui entend un signal venu de la Lune, toutes les nuits',
  'des imprimantes 3D communautaires qui refusent de fabriquer des clés',
  'une constellation de satellites qui éclaire une forêt entière, sans raison apparente',
  'des robots de déminage qui commencent à désamorcer les rancunes',
  'un système de vote en ligne qui compte deux fois les abstentions',
  'des caméras publiques qui reconnaissent la peur avant le crime',
  'un data-center enfoui qui souffle un air plus froid que la planète',
  'des algorithmes de recrutement qui embauchent pour des vies que les candidats n\'ont pas vécues',
  'un réacteur de fusion municipal dont la chaleur dessine des formes',
  'des drones agricoles qui plantent en cercles autour des maisons abandonnées',
  'une expérience de compression du temps dans une usine pilote',
  'des fresques murales qui se mettent à jour toutes seules avec les rumeurs',
  'un traducteur de foules qui résume les manifestations en une phrase silencieuse',
  'une archive orbitale qui signale que la Terre a déjà été vide, une fois',
];

/** SF : sociétés de demain. */
export const SF_SOCIETES: string[] = [
  'une ville qui vend ses nuits à des visiteurs de l\'autre hémisphère',
  'un district entièrement réglé par la dette de sommeil',
  'une communauté qui vote chaque semaine sur les émotions autorisées',
  'des immeubles qui hébergent leurs habitants selon leur horloge biologique',
  'une économie du silence : on paie pour ne pas être dérangé',
  'des écoles qui enseignent les métiers qu\'elles inventent chaque année',
  'une société de la preuve : tout engagement doit être démontré',
  'des quartiers qui troquent les compétences avant l\'argent',
  'un gouvernement qui publie les décisions avant de les prendre, pour ajuster',
  'des familles composées par algorithme, avec un droit d\'échange annuel',
  'une ville-flottante qui suit les courants de pensée des autres villes',
  'des retraites où l\'on peut aussi gagner du temps pour d\'autres',
  'un réseau de soins qui soigne d\'abord le quartier, puis la personne',
  'des règles d\'urbanisme souples : les bâtiments se construisent selon les besoins parlés',
  'une économie de la réparation où casser vaut plus cher que réparer',
  'des conseils de quartier qui arbitrent les bruits de la mémoire collective',
  'un système scolaire à vocation unique, choisie à dix ans, réversible à chaque solstice',
  'des monuments qui changent de nom selon les absences',
  'une sécurité publique qui prévient les accidents en réorganisant les rues selon les souvenirs',
  'des marchés qui n\'échangent que du temps entre voisins',
  'une constitution qui protège le droit à l\'oubli autant qu\'à la mémoire',
  'des bibliothèques vivantes : chaque habitant peut être emprunté pour une conversation',
  'un système de santé qui prescrit des promenades dans les lieux aimés',
  'des transports publics gratuits aux heures où la ville a besoin de se parler',
  'une administration qui répond par les faits, jamais par les formulaires',
  'des réserves de calme : des espaces où l\'on ne peut pas être contacté',
  'une justice de réparation qui passe par des objets fabriqués ensemble',
  'des saisons artificielles pour que chaque génération garde ses repères',
  'une ville qui rend hommage chaque hiver aux décisions courageuses',
  'des fêtes du début : célébrer les commencements, pas les fins',
];

/** Policier : crimes et affaires. */
export const POLICIER_CRIMES: string[] = [
  'un vol qui rapporte tout sauf l\'objet annoncé',
  'une disparition déclarée par la victime elle-même',
  'un incendie qui a pris dans la pièce où personne n\'était',
  'un meurtre sans corps, avec trois aveux contradictoires',
  'une lettre anonyme qui annonce le crime avec une semaine d\'avance',
  'un cambriolage où rien ne manque, mais tout est déplacé de quelques centimètres',
  'un empoisonnement lent : chaque invité a bu la même coupe, un seul est mort',
  'un accident de voiture sans traces de frein, sur une route en pente douce',
  'un suicide en scène : la porte était verrouillée de l\'intérieur, la clé introuvable',
  'un enlèvement dont la rançon est payée, mais jamais demandée',
  'un cambriolage de labo où seul un résultat de test a disparu',
  'une noyade dans une rivière à sec, un jour de pluie',
  'un meurtre refait à l\'identique dix ans plus tard, dans la même rue',
  'un vol de chef-d\'œuvre remplacé par une copie si bonne que le musée n\'a pas remarqué',
  'une chute d\'escalier qui laisse des traces en montant',
  'un échange de documents qui ne change le sort de personne, sauf un',
  'un coup de feu entendu par tout le quartier, et aucune arme nulle part',
  'une noyade dans une baignoire remplie d\'eau de mer',
  'un meurtre pendant un repas : le couteau est sur la table, les mains propres',
  'une disparition de chien qui mène à la première vraie piste',
  'un testament volé avant l\'ouverture, et un héritier qui n\'existait pas',
  'un faux en écriture passé à l\'encre invisible, révélé par l\'humidité',
  'un cambriolage de pharmacie : seule la liste des clients est emportée',
  'un accident du travail dans une usine à l\'arrêt depuis un an',
  'un poison rare dans le thé d\'un collectionneur de poisons',
  'une agression sans mobile apparent, avec une montre arrêtée à la mauvaise heure',
  'un trafic de fausses pièces anciennes, découvert par un numismate amateur',
  'un meurtre parfaitement exécuté sauf un détail : l\'assassin a toussé',
  'une lettre de démission signée le jour du crime, jamais postée',
  'un braquage de banque où le braqueur connaît le code de la salle des coffres',
];

/** Policier : indices et pistes. */
export const POLICIER_INDICES: string[] = [
  'un mégot de marque introuvable dans le pays, mais fumé sur place',
  'une empreinte de chaussure neuve dans la poussière ancienne',
  'un carnet de tickets qui compte un trajet de plus que les jours',
  'une poignée de main relevée sur la poignée intérieure d\'une porte',
  'une photographie développée en double, dont une copie a été tachée volontairement',
  'un mot griffonné dans une langue que le mort ne parlait pas',
  'une trace de glaise rouge, alors que la région est calcaire',
  'un parfum précis sur un vêtement jamais porté',
  'un horodatage de caméra qui ne correspond à l\'éclairage de la scène',
  'une bague retournée sur un doigt : le geste d\'une fuite précipitée',
  'un enregistrement de répondeur avec un bruit de fond impossible',
  'une facture conservée pour la morte-saison, alors que le mort était économe',
  'des cendres de papier dans un poêle froid, et le registre effacé',
  'une fenêtre fermée de l\'extérieur, alors qu\'elle était ouverte de l\'intérieur',
  'un emploi du temps public qui ment pour une seule heure, la bonne',
  'un paquet de lettres avec le cachet du jour du crime, jamais ouvertes',
  'une trace de roue trop étroite pour le véhicule déclaré',
  'un réveil réglé à une heure qui n\'existe pas ce jour-là',
  'des gouttes de cire sur un tapis, alors que personne n\'a allumé de bougie',
  'un livre ouvert à une page qui commente exactement le crime',
  'une bouteille de gaz partiellement vide dans un appartement sans gaz',
  'un ticket de cinéma pour un film qui n\'est jamais sorti',
  'des traces d\'eau sur le rebord d\'une fenêtre, un jour sans pluie',
  'un télescope pointé sur une chambre vide depuis des semaines',
  'un double des clés confié à quelqu\'un dont personne ne parle',
  'une dette remboursée le jour du meurtre, par virement anonyme',
  'un sachet de thé infusé trop longtemps : quelqu\'un est resté, puis est parti sans boire',
  'une carte routière lavée : seule la route du crime est effacée',
  'un répondeur avec un message effacé dont le silence reste',
  'une montre-bracelet au poignet du mort, marquée à une heure future',
];

/** Policier : suspects et mobiles. */
export const POLICIER_SUSPECTS: string[] = [
  'l\'héritière trop calme, qui connaît déjà la date de lecture du testament',
  'le notaire qui a recopié le testament trois fois, et qui détient la quatrième version',
  'le voisin qui arrose les plantes à heures fixes, sauf depuis le crime',
  'la secrétaire qui a pris une retraite soudaine le jour du drame',
  'le journaliste qui avait une source inavouable, et qui n\'écrit plus',
  'le médecin qui a signé l\'acte de décès avec un peu trop d\'assurance',
  'le collectionneur qui voulait la pièce volée, et qui sourit des indices',
  'le jardinier qui connaît les allées mieux que les propriétaires',
  'l\'ancien associé ruiné, dont la ruine date d\'un mois avant le crime',
  'le facteur qui connaissait les horaires de tout le quartier',
  'le projectionniste du cinéma, témoin de la scène sans le savoir',
  'la libraire qui a vendu un livre à la victime, et le sait par cœur',
  'le pompiste qui a fait le plein de la voiture du crime, trois jours après',
  'le pharmacien qui a délivré l\'ordonnance fatale, avec un doute',
  'l\'assureur qui avait tout à gagner et rien à prouver',
  'le professeur de musique dont les cours couvraient l\'heure du crime',
  'la marchande de journaux qui n\'a pas vu passer le suspect, alors que tout le monde l\'a vu',
  'le traducteur du testament, seul capable d\'en contester un mot',
  'l\'ancien employé de maison, congédié pour une broutille, qui garde un double des clés',
  'le chauffeur de taxi dont la course n\'apparaît sur aucun reçu',
  'le barman qui se souvient d\'un client qui payait en petite monnaie exacte',
  'la costumière du théâtre, qui sait se déguiser en n\'importe qui',
  'l\'écrivain local qui décrivait le crime dans son avant-dernier chapitre',
  'le notaire adjoint qui a tout vu et n\'a rien dit',
  'le voyageur de commerce présent à chaque faux alibi',
  'la fleuriste qui a livré des fleurs pour une pendaison de crémaillère, un jour d\'enterrement',
  'l\'agent immobilier qui a gardé les clés de la maison vendue',
  'le cousin éloigné soudainement riche, incapable de dire d\'où vient l\'argent',
  'la voisine qui écoute la radio toute la journée, et cite le crime par cœur',
  'le clerc de notaire qui sait lire les testaments à l\'envers, pour les autres',
];

/** Historique : complots et intrigues. */
export const HISTORIQUE_COMPLOTS: string[] = [
  'une lettre volée qui changerait l\'équilibre des offices, si elle était publiée',
  'un testament qui n\'existe qu\'en deux exemplaires, tous les deux convoités',
  'une dette de sang contractée par un aïeul, exigée aujourd\'hui',
  'un convoi secret qui traverse la région avec une caisse sous scellé',
  'une alliance de commerce qui cache une promesse de mariage',
  'un détournement de fonds de la confrérie, soigneusement décoré en charité',
  'un plan de siège recopié en code, qui tombe entre des mains neutres',
  'une relique recouverte de dorure pour en cacher une autre',
  'un traité signé deux fois, avec deux dates, pour deux rois',
  'une liste de noms que l\'on brûle et que l\'on refait chaque année',
  'un inventaire après décès qui omet la pièce la plus précieuse',
  'une charte de village falsifiée pour annexer un moulin et une servitude',
  'un héritier supposé mort, et un notaire qui tient deux testaments',
  'une correspondance chiffrée entre deux familles que tout oppose',
  'un espion qui change de camp à chaque lettre, et tient le registre secret',
  'une élection de confrérie truquée par des voix achetées en grain',
  'un partage d\'eaux de rivière qui décide du sort de trois moulins',
  'un siège en préparation, et des vivres qui ont déjà changé de mains',
  'une dot gonflée par des terres qu\'on ne possède pas encore',
  'un procès pour sorcellerie qui vise en réalité un bail minier',
  'un moine copiste qui insère une clause dans un contrat à chaque copie',
  'une route nouvelle qui dévaluerait les péages de la famille rivale',
  'un coup d\'état de clocher : changer les sonneurs pour changer les annonces',
  'un inventaire de bibliothèque qui recèle un plan de défense',
  'une lettre de crédit payable à vue, dans une ville où personne ne paie',
  'un concordat signé sous la pluie, dont l\'encre a coulé sur un mot',
  'un bijou de couronne remplacé par un faux, et personne n\'ose le dire',
  'une peste de bestiaux provoquée pour ruiner un abreuvoir',
  'une inscription sur la pierre d\'un pont qui change de propriétaire à la crue',
  'une promesse d\'asile vendue deux fois, le même jour',
];

/** Historique : rencontres et personnages d'époque. */
export const HISTORIQUE_PERSONNAGES: string[] = [
  'un cartographe qui dessine mieux la région que ceux qui y vivent',
  'une guérisseuse qui connaît les plantes mieux que le médecin du bourg',
  'un colporteur de nouvelles qui vend les rumeurs avant les tissus',
  'un garde-chasse qui protège les braconniers contre le seigneur',
  'une lavandière qui entend tout ce que les draps cachent',
  'un organiste aveugle qui connaît les secrets de chaque pierre',
  'un maître d\'école qui enseigne l\'histoire autrement que le pouvoir',
  'une sage-femme reçue partout, et qui ne parle jamais',
  'un greffier qui écrit deux procès-verbaux : le vrai et le publié',
  'un batelier qui connaît les gués et les contrefaçons du fleuve',
  'un haleur de péniche trop instruit pour sa condition',
  'une brodeuse dont les motifs transmettent des messages codés',
  'un tanneur dont l\'odeur écarte même les informateurs',
  'un archer de la milice qui tire trop bien pour son rang',
  'une tenancière d\'auberge qui héberge les deux camps, sans choisir',
  'un fauconnier qui dresse les oiseaux pour les lettres et la chasse',
  'une terre-neuve de marais qui guide les voyageurs contre un sou',
  'un tonnelier qui mesure l\'honnêteté des marchands au bois des fûts',
  'un clerc de notaire aux doigts tachés d\'encre et de silence',
  'une voyageuse de retour, qui parle une langue que plus personne ne parle',
  'un apothicaire dont les pots gardent des étiquettes effacées',
  'un sonneur de cloches qui sonne les heures et les alertes, jamais les fêtes',
  'une fileuse qui garde un écheveau de laine de chaque client',
  'un régisseur qui connaît les comptes mieux que le château',
  'un pelleteur de fossés qui sait ce que la terre a recouvert',
  'une couturière de deuil, spécialiste des habits des disparus',
  'un meunier suspect de favoriser un moulin au détriment des autres',
  'un passeur de frontières, discret, qui ne traverse jamais lui-même',
  'une prieure qui reçoit les confidences comme les pierres, sans les rendre',
  'un apprenti imprimeur qui a vu la preuve dans les caractères',
];

/** Historique : objets et découvertes d'époque. */
export const HISTORIQUE_OBJETS: string[] = [
  'un écriteau de bois gravé des droits de passage d\'un village disparu',
  'une monnaie au nom d\'un roi dont personne n\'a entendu parler',
  'une carte marine avec une île portant le nom du héros',
  'un reliquaire vide, scellé, et un procès pour savoir ce qu\'il contient',
  'un traité agricole annoté de la main d\'un inconnu',
  'une cloche de couvre-feu fêlée, dont le son porte jusqu\'au camp adverse',
  'un passeport de marchand avec un privilège de tonnage exagéré',
  'un éventail de cour dont les dessins cachent une correspondance',
  'une bague d\'alliance gravée de deux noms, dont un effacé',
  'un moule à hosties marqué du blason d\'une famille assemblée',
  'un semainier de planification domaniale rempli d\'heures impossibles',
  'un canif de marin avec une lame cachée, et une date gravée',
  'un registre de baptêmes avec une page arrachée, et une autre recopiée',
  'un heaume de tournoi portant un coup qui n\'a jamais été porté',
  'une mesure de grain graduée à l\'ancienne étalon, jamais vérifiée',
  'un horaire de diligences où figue une route qui n\'existe plus',
  'un banc d\'église numéroté pour une famille qui n\'y siégeait jamais',
  'une enseigne de corporation avec le métier changé d\'un mot',
  'un billet de loterie royal daté de l\'année du grand hiver',
  'un fichier de péage avec une colonne pour les exemptés, remplie',
  'un évangéliaire avec une feuille cousue dans la reliure',
  'un sachet de graines d\'un potager princier, avec une étiquette secrète',
  'un étendard réparé tant de fois qu\'il ne reste que les symboles',
  'une serrure de coffre à deux clés, dont une seule a été forgée',
  'un inventaire de ferme avec plus de bêtes que le village n\'en a jamais vu',
  'un compas de marine au cadran signé par une femme',
  'un tableau de notables avec un personnage repeint par-dessus',
  'un acte de vente qui transfère un château et une malédiction, au même prix',
  'un verre à pied gravé du toast d\'un mariage, d\'une date impossible',
  'un bouquin de comptes avec une colonne de dépenses en lettres de sang',
];

/**
 * Tables spécifiques par genre : 3 catégories chacune.
 * La clé = code de genre (match GameParams['genre']).
 */
export const BRIQUES_PAR_GENRE: Record<string, { categorie: string; elements: string[] }[]> = {
  horreur: [
    { categorie: 'Créature ou présence', elements: HORREUR_CREATURES },
    { categorie: 'Menace humaine ou psychologique', elements: HORREUR_HUMAINE },
    { categorie: 'Le quotidien qui se fissure', elements: HORREUR_QUOTIDIEN },
    { categorie: 'Lieu oppressant', elements: HORREUR_LIEUX },
  ],
  romance: [
    { categorie: 'Situation familiale ou cercle proche', elements: ROMANCE_SITUATIONS_FAMILIALES },
    { categorie: 'Obstacle entre les deux personnes', elements: ROMANCE_OBSTACLES },
    { categorie: 'Moment-clé du rapprochement', elements: ROMANCE_MOMENTS },
  ],
  fantasy: [
    { categorie: 'Artefact magique', elements: FANTASY_ARTEFACTS },
    { categorie: 'Créature ou peuple légendaire', elements: FANTASY_CREATURES },
    { categorie: 'Quête ou épreuve', elements: FANTASY_EPREUVES },
  ],
  science_fiction: [
    { categorie: 'Technologie étrange', elements: SF_TECHNOLOGIES },
    { categorie: 'Découverte ou menace', elements: SF_MENACES },
    { categorie: 'Société de demain', elements: SF_SOCIETES },
  ],
  policier: [
    { categorie: 'Crime ou affaire', elements: POLICIER_CRIMES },
    { categorie: 'Indice ou piste', elements: POLICIER_INDICES },
    { categorie: 'Suspect ou mobile', elements: POLICIER_SUSPECTS },
  ],
  historique: [
    { categorie: 'Complot ou intrigue', elements: HISTORIQUE_COMPLOTS },
    { categorie: 'Rencontre d\'époque', elements: HISTORIQUE_PERSONNAGES },
    { categorie: 'Objet ou découverte d\'époque', elements: HISTORIQUE_OBJETS },
  ],
};

// ============================================================================
// PROFILS DE RYTHME NARRATIF (48 profils, 8 par genre)
// Informés par l'étude des 47 best-sellers (docs/5-ecriture-narrative/
// ce-que-veulent-les-lecteurs.txt) : chaque profil est tracé vers les
// livres dont il est tiré. PIOCHÉ à la création et appliqué à tout le
// roman (bible + chapitres via params.rythme).
// ============================================================================

export interface RythmeNarratif {
  id: string;
  nom: string;
  inspirePar: string;
  consigne: string;
}

export const RYTHMES_PAR_GENRE: Record<string, RythmeNarratif[]> = {
  horreur: [
    {
      id: 'horreur_infiltration',
      nom: 'Infiltration du quotidien',
      inspirePar: 'Simetierre, The Haunting of Hill House',
      consigne: 'Installation réaliste et longue de la vie ordinaire (famille, maison, voisins) ; la peur s\'infiltre par couches discrètes qui prennent du sens tardivement. Pics d\'angoisse rares mais lourds, longues respirations entre eux, fin qui hante. Le lecteur doit aimer le quotidien avant d\'avoir peur.',
    },
    {
      id: 'horreur_compte_a_rebours',
      nom: 'Enquête froide à compte à rebours',
      inspirePar: 'Ring',
      consigne: 'Narration clinique et distante qui tient l\'angoisse à distance, une règle de danger énoncée tôt (délai, cycle, condition) transformée en compte à rebours permanent. La peur se propage par contagion ; climax tardif, concentré et violent après une progression lente.',
    },
    {
      id: 'horreur_double_fil',
      nom: 'Double fil resserré',
      inspirePar: 'Le Silence des agneaux',
      consigne: 'Chapitres courts alternant une scène de huis clos oppressant (dialogue lent, tension sourde) et une scène d\'action/d\'enquête. Une victime captive ou un enjeu daté sert de compte à rebours ; les deux fils convergent en accélération brutale dans le dernier quart.',
    },
    {
      id: 'horreur_miroir',
      nom: 'Miroir passé / présent',
      inspirePar: 'Ça',
      consigne: 'Double temporalité qui se répond (enfance / âge adulte) : chaque époque éclaire l\'autre et la menace se personnalise selon les peurs propres des personnages. Montée parallèle des deux fils, quotidien et étrangeté mêlés, interludes documentaires en coupe.',
    },
    {
      id: 'horreur_echelons',
      nom: 'Épidémie en échelons',
      inspirePar: 'La Conjuration primitive',
      consigne: 'Incidents qui s\'intensifient en échelons réguliers : chaque chapitre ajoute une pièce au code de la menace, la gravité grimpe par paliers (premier signal, premier mort, série, escalade). Points de vue d\'enquête alternés, mystère dévoilé progressivement.',
    },
    {
      id: 'horreur_epistolaire',
      nom: 'Fragments qui s\'assemblent',
      inspirePar: 'Dracula',
      consigne: 'Récit à plusieurs mains (journal, lettres, rapports, témoignages), chaque narrateur ne tenant qu\'un fragment de vérité : le lecteur assemble le puzzle et anticipe avant les personnages. Montée lente et majestueuse, terreur frontale espacée mais décisive, chasse finale accélérée.',
    },
    {
      id: 'horreur_suggestion',
      nom: 'Suggestion sans vision frontale',
      inspirePar: 'The Haunting of Hill House',
      consigne: 'Jamais de monstre ou de menace montrés en face : froid, bruits, écritures, présences ressenties. Phénomènes d\'abord anodins qui s\'individualisent et ciblent le héros. Fin ambiguë où l\'on ne sait pas ce qui était réel - l\'angoisse survit à la dernière page.',
    },
    {
      id: 'horreur_labyrinthe',
      nom: 'Structure qui se dérègle',
      inspirePar: 'House of Leaves',
      consigne: 'Le récit imite la menace : chapitres qui se contredisent, couches narratives enchâssées, notes et documents qui débordent, le lecteur désorienté comme le héros. Les lieux changent de taille et de forme sans explication, l\'emprisonnement se ressent dans la forme même.',
    },
  ],
  fantasy: [
    {
      id: 'fantasy_quete_contemplative',
      nom: 'Quête contemplative',
      inspirePar: 'Le Seigneur des Anneaux, Terremer',
      consigne: 'Voyage structuré par l\'alternance délibérée entre périls et longues respirations (halte, contemplation, conversations qui comptent). La menace monte très progressivement, la victoire est concentrée à la fin et se paie. Peu de batailles : le monde se découvre avec le héros.',
    },
    {
      id: 'fantasy_crises_politiques',
      nom: 'Crises politiques successives',
      inspirePar: 'Le Trône de fer',
      consigne: 'Multiples points de vue en chapitres courts et alternés qui font progresser plusieurs fronts à des vitesses différentes. Retournements violents qui sanctionnent la logique du monde plus que le mérite du héros : la défaite est toujours possible, la survie se mérite.',
    },
    {
      id: 'fantasy_recit_cadre',
      nom: 'Récit dans le récit',
      inspirePar: 'Le Nom du vent',
      consigne: 'Un cadre présent (statique, mélancolique) enveloppe l\'histoire racontée au passé : deux niveaux qui se répondent. Progression par compétences maîtrisées une à une, avec des temps de vie (musique, amitié, amour) qui épaississent l\'apprentissage au lieu de le presser.',
    },
    {
      id: 'fantasy_modulaire',
      nom: 'Modulaire façon série',
      inspirePar: 'Harry Potter',
      consigne: 'Chapitres courts centrés sur l\'action, chacun ouvrant et refermant sa propre dynamique : on tourne les pages par structure, pas par curiosité des fins. Escalade graduelle des enjeux et des pertes : les victoires deviennent de plus en plus coûteuses.',
    },
    {
      id: 'fantasy_cascade',
      nom: 'Cascade de révélations',
      inspirePar: 'Mistborn',
      consigne: 'Rythme rapide, séquences d\'action cinétiques, révélations régulières où chaque réponse ouvre un nouveau mystère. Les règles du monde sont établies dès le début et les climax les respectent rigoureusement : tout se résout selon les règles annoncées.',
    },
    {
      id: 'fantasy_cercles',
      nom: 'Cercles concentriques',
      inspirePar: 'La Passe-miroir',
      consigne: 'Intrigue où le décor et les enjeux s\'élargissent par cercles successifs. Indices semés très tôt qui ne se referment que bien plus tard, tensions accumulées (secrets, complots, disparitions) plutôt que rebondissements perpétuels.',
    },
    {
      id: 'fantasy_initiation',
      nom: 'Initiation resserrée',
      inspirePar: 'La Quête d\'Ewilan',
      consigne: 'Quête initiatique classique et resserrée : entrée dans le monde, équipée, épreuves, affrontement final. Chapitres courts, rebondissements fréquents, humour qui contrebalance le danger, progression en confiance et en maîtrise.',
    },
    {
      id: 'fantasy_entrelacee',
      nom: 'Trames entrelacées',
      inspirePar: 'Le Seigneur des Anneaux (tomes 2-3)',
      consigne: 'Plusieurs fils narratifs entrelacés à la manière des romans médiévaux : on passe de l\'un à l\'autre aux moments critiques, chacun avançant vers la convergence finale. Escalade très longue, contemplation et péril alternés, grands affrontements concentrés dans le dernier tiers.',
    },
  ],
  science_fiction: [
    {
      id: 'sf_documentaire_puis_spirale',
      nom: 'Documentaire puis spirale',
      inspirePar: 'Dune',
      consigne: 'Départ lent, presque documentaire : le monde s\'installe par couches (écologie, politique, culture) avec des interludes qui le densifient. Puis l\'accélération devient une spirale de rebondissements jusqu\'au dénouement. Le rythme épouse la trajectoire de tragédie.',
    },
    {
      id: 'sf_chaine_problemes',
      nom: 'Chaîne problème → solution → contretemps',
      inspirePar: 'Seul sur Mars',
      consigne: 'Mécanisme implacable : chaque solution trouvée est suivie d\'un nouveau contretemps et d\'un nouveau défi. Mini-cliffhangers à chaque chapitre, alternance du journal personnel (voix proche, humour) et de la vue d\'ensemble (équipe, monde).',
    },
    {
      id: 'sf_heist',
      nom: 'Heist effréné',
      inspirePar: 'Neuromancien',
      consigne: 'Structure de coup monté : recrutement du héros, constitution d\'une équipe improbable, missions qui s\'enchaînent vers un sommet final. Prose dense et rythme effréné, le monde se révèle par immersion sans exposition didactique, chaque mission coûte quelque chose.',
    },
    {
      id: 'sf_fragmente',
      nom: 'Fragmenté présent / passé',
      inspirePar: 'La Servante écarlate',
      consigne: 'Récit à la première personne qui navigue sans cesse entre un présent oppressant et des flashbacks de liberté : les souvenirs cisaillent la tension de l\'enfermement. Flux de conscience, ellipses mentales, énigmes suspendues, angoisse sourde, fin ouverte.',
    },
    {
      id: 'sf_double_temporalite',
      nom: 'Double temporalité + révélations en cascade',
      inspirePar: 'Le Problème à trois corps',
      consigne: 'Deux époques reliées par une décision ancienne, chacune éclairant l\'autre ; la densité scientifique est coupée par des scènes d\'action et des mystères à résoudre. Chaque chapitre ajoute une pièce du puzzle, les révélations s\'enchaînent en cascade dans la deuxième moitié.',
    },
    {
      id: 'sf_conceptuel',
      nom: 'Coup de théâtre conceptuel',
      inspirePar: 'Fondation',
      consigne: 'Suite d\'épisodes-crises, chacun présentant une menace apparemment insoluble puis un retournement logique qui redéfinit la situation pour la suite. Grands sauts temporels entre les épisodes, narration mesurée où l\'idée prime mais les personnages restent le contrepoint émotionnel.',
    },
    {
      id: 'sf_chronique_ellipses',
      nom: 'Chronique à grandes ellipses',
      inspirePar: 'La Guerre éternelle',
      consigne: 'Succession de missions séparées par des ellipses temporelles de plus en plus vertigineuses : le temps est la vraie matière du récit. Ton factuel et retenu qui contraste avec la détresse humaine qu\'il recouvre, portraitures brèves et poignantes entre deux ellipses.',
    },
    {
      id: 'sf_paliers_jeu',
      nom: 'Paliers de jeu + deadline',
      inspirePar: 'Ready Player One',
      consigne: 'Structure strictement ludique : chaque étape est une quête (indice, énigme, épreuve, récompense) avec des paliers et une deadline qui crée l\'urgence. Chapitres courts et rythme rapide, incursions dans la vie réelle qui redonnent du poids aux enjeux.',
    },
  ],
  policier: [
    {
      id: 'policier_procedural',
      nom: 'Procédural en trois parties',
      inspirePar: 'Le Crime de l\'Orient-Express',
      consigne: 'Trois temps nets : le crime, les interrogatoires méthodiques (même schéma pour chaque suspect, mécanique des alibis installée), puis le dénouement double qui effondre tout en cascade. Rythme répétitif assumé qui récompense la patience du lecteur.',
    },
    {
      id: 'policier_relais',
      nom: 'Relais d\'énigmes, zéro temps mort',
      inspirePar: 'Da Vinci Code',
      consigne: 'Chapitres de deux à quatre pages, points de vue alternés en miroir (héros / poursuivants), compte à rebours permanent. Chaque énigme résolue révèle l\'adresse de la suivante : la tension ne retombe jamais, chaque fin de chapitre pousse vers le suivant.',
    },
    {
      id: 'policier_dialogue_action',
      nom: 'Dialogue lent / action alternée',
      inspirePar: 'Le Silence des agneaux',
      consigne: 'Alternance stricte : scènes d\'interrogatoire oppressantes où chaque dialogue livre un indice crypté (tension lente), et scènes d\'enquête terrain (action, découvertes). Compte à rebours final qui accélère brutalement après une première moitié patiente.',
    },
    {
      id: 'policier_documentaire',
      nom: 'Documentaire lent + fulgurances',
      inspirePar: 'Millénium 1',
      consigne: 'Longues séquences méthodiques (archives, listes, chiffres, photos) ponctuées de fulgurances violentes : le contraste de rythme est assumé. Les indices sont des objets matériels que le lecteur assemble en même temps que l\'enquêteur.',
    },
    {
      id: 'policier_atmospherique',
      nom: 'Démarrage atmosphérique puis accélération',
      inspirePar: 'Pars vite et reviens tard',
      consigne: 'Ouverture lente et atmosphérique (le décor, les habitudes) avant l\'accélération de la série de crimes. L\'enquête avance par intuitions et parallélismes de destins plutôt que par piste unique ; la révélation finale re-sémantise les détails anodins du début.',
    },
    {
      id: 'policier_course',
      nom: 'Course contre la montre',
      inspirePar: 'Ne le dis à personne',
      consigne: 'Ordres anonymes à durée limitée sous menace : chaque pan de vérité en révèle un autre, chapitres courts et phrases sèches, révélations en cascade. Les twists sont préparés par rétro-ingénierie : de petits détails posés dès les premières pages.',
    },
    {
      id: 'policier_double_enquete',
      nom: 'Double enquête, suspects éliminés',
      inspirePar: 'Le Bonhomme de neige',
      consigne: 'Deux temporalités (lettres du passé / enquête présente) et deux fronts (le tueur, et la corruption interne qui sabote les avancées). Les suspects se succèdent et sont éliminés au compte-gouttes par des fausses pistes correctement démontées.',
    },
    {
      id: 'policier_poupees_russes',
      nom: 'Poupées russes 1999 / aujourd\'hui',
      inspirePar: 'L\'Affaire Alaska Sanders',
      consigne: 'Construction en poupées russes : alternance entre deux époques, chapitres courts, flashbacks qui re-contextualisent chaque témoignage. Une nouvelle « vérité » complète tombe régulièrement, chacune contredisant la précédente tout en réutilisant les mêmes faits.',
    },
  ],
  historique: [
    {
      id: 'historique_fresque',
      nom: 'Fresque à horloge narrative',
      inspirePar: 'Les Piliers de la Terre',
      consigne: 'Longue fresque multipersonnages dont chaque partie correspond à une étape d\'un projet concret (construire, survivre, s\'élever) qui sert d\'horloge narrative sur une génération. Larges ellipses temporelles entrecoupées de scènes-chapitres à fort suspense, cliffhanger par chapitre.',
    },
    {
      id: 'historique_polar',
      nom: 'Polar à compte à rebours',
      inspirePar: 'Le Nom de la Rose',
      consigne: 'Enquête scandée par une contrainte rigoureuse (heures, jours, liturgie) qui transforme le récit en compte à rebours. Dialogue philosophique et action alternés, montée vers un lieu interdit, progression par fausses pistes et redécouvertes.',
    },
    {
      id: 'historique_feuilleton',
      nom: 'Feuilleton théâtral',
      inspirePar: 'La Reine Margot, Les Trois Mousquetaires',
      consigne: 'Succession d\'épisodes aux couleurs variées, chacun clos par un coups de théâtre ou un rebondissement qui appelle la suite. Scènes courtes, quiproquos, incognitos, actions parallèles : rythme galopant de duels, poursuites et missions.',
    },
    {
      id: 'historique_obsession',
      nom: 'Montée obsessionnelle',
      inspirePar: 'Le Parfum',
      consigne: 'Structure en parties qui miment l\'évolution d\'une obsession (apprentissage, isolement, perfection, consécration). Longues séquences de progression obsessionnelle et pointes de tension criminelle, narrateur à l\'ironie savante, dénouement qui renverse le sens de la quête.',
    },
    {
      id: 'historique_memoire',
      nom: 'Mémoire de la cour',
      inspirePar: 'Wolf Hall',
      consigne: 'Le rythme mime le fonctionnement de la mémoire : sauts, boucles, retours en arrière, chaque scène ancrée dans l\'instant présent. Scènes de cour denses, conversations à double sens, basculements brutaux, progression par l\'ascension d\'un personnage.',
    },
    {
      id: 'historique_symphonie',
      nom: 'Symphonie en plans parallèles',
      inspirePar: 'La Chute des géants',
      consigne: 'Plusieurs familles dispersées vivent les mêmes grands événements sous des angles opposés : contraste permanent, rythme de roman-chronique avec larges ellipses et dates-chapitres, chaque séquence dramatisée avec un fort cliffhanger.',
    },
    {
      id: 'historique_immersion_lente',
      nom: 'Immersion lente puis basculement',
      inspirePar: 'Les Piliers de la Terre (installation), romans de moeurs',
      consigne: 'Installation prolongée dans les mœurs de l\'époque (métiers, objets, odeurs, hiérarchies, croyances) par des scènes de vie quotidienne, avant qu\'un grand événement historique ne bascule tout, vécu de l\'intérieur par le héros. La lenteur initiale rend le bouleversement colossal.',
    },
    {
      id: 'historique_itineraire',
      nom: 'Itinéraire d\'époque',
      inspirePar: 'Les Trois Mousquetaires (odyssée)',
      consigne: 'Odyssée : le héros traverse lieux, classes sociales et milieux différents de l\'époque, chaque étape révélant une facette du monde et un nouvel obstacle. Alliances et trahisons le long de la route, escalade vers un affrontement final, épisodes autonomes reliés par la quête.',
    },
  ],
  romance: [
    {
      id: 'romance_point_bas',
      nom: 'Point bas aux deux tiers',
      inspirePar: 'Orgueil et Préjugés, Beach Read',
      consigne: 'Joutes verbales et malentendus qui nourrissent la tension, refus ou rupture au point bas des deux tiers, puis une révélation (lettre, aveu, prise de conscience) qui retourne tout. Chapitres courts, ironie distillée, retournements domestiques qui relancent le désir.',
    },
    {
      id: 'romance_double_temporalite',
      nom: 'Double temporalité + escalade émotionnelle',
      inspirePar: 'It Ends with Us',
      consigne: 'Le présent de la relation est éclairé par des flashbacks (journal, premier amour) qui expliquent les choix du héros. Chapitres courts, style minimal, émotion à fleur de page : escalade des tensions nuancée, point bas salutaire, résolution par un choix assumé.',
    },
    {
      id: 'romance_compte_a_rebours',
      nom: 'Compte à rebours de contrainte',
      inspirePar: 'Beach Read',
      consigne: 'Une contrainte temporelle claire (défi, délai, saison) sert d\'horloge au rapprochement : chaque chapitre forme un arc complet et fait avancer la relation d\'un cran. Lenteur assumée vers le baiser attendu, point bas aux deux tiers, résolution en choix décisif.',
    },
    {
      id: 'romance_episodique',
      nom: 'Épisodique, pic par chapitre',
      inspirePar: 'After',
      consigne: 'Chapitres courts, quasi épisodiques, qui se terminent presque tous sur un pic émotionnel ou un cliffhanger : la mécanique du « encore un chapitre ». Cycle attraction-répulsion entre les deux, réconciliations et doutes, point bas majeur, rédemption amorcée ensuite.',
    },
    {
      id: 'romance_recit_cadre',
      nom: 'Récit-cadre contemplatif',
      inspirePar: 'The Notebook',
      consigne: 'Un présent (vieillesse, maison de retraite) encadre le flashback de l\'histoire d\'amour : les deux temporalités se répondent et se rejoignent. Rythme lent, contemplatif, prose nostalgique, deux courses contre la montre qui se redoublent, émotion par scènes simples et vraies.',
    },
    {
      id: 'romance_mystere',
      nom: 'Mystère + rapprochement',
      inspirePar: 'Et si c\'était vrai...',
      consigne: 'Une énigme (mystère médical, situation impossible) motive la rencontre et sert de moteur au rapprochement ; le doute sur la réalité sert de point bas. Chapitres courts, dialogues qui font avancer l\'action, échéance qui accélère la fin.',
    },
    {
      id: 'romance_road_movie',
      nom: 'Road movie + twists',
      inspirePar: 'La Fille de papier',
      consigne: 'Une irruption spectaculaire lance l\'aventure commune (poursuite, voyage, enquête) : l\'action et la montée amoureuse alternent, chapitres très courts, révélations régulières. Point bas sur un doute fondamental, résolution lumineuse où la fiction sauve le réel.',
    },
    {
      id: 'romance_multiple',
      nom: 'Couples multiples, montée rassurante',
      inspirePar: 'Montana Sky',
      consigne: 'Plusieurs points de vue et deux couples ou plus : chaque sous-intrigue reçoit son temps de développement. L\'intimité se construit à travers le quotidien partagé (travaux, repas, confidences) ; montée lente et rassurante, danger au point bas, happy end.',
    },
  ],
};